# typed: false
# frozen_string_literal: true

# Homebrew formula for dsd (DashDiag) — generated by scripts/gen-homebrew-formula.sh.
# Do not hand-edit; re-run the generator for a new release.
class Dsd < Formula
  desc "OBD diagnostics for your Linux server — one command, full picture"
  homepage "https://dashdiag.sh"
  version "0.6.1"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/keyorixhq/dashdiag/releases/download/v0.6.1/dsd-darwin-arm64"
      sha256 "cda9dc87c60e5f14cd346f29d5511433d03e55080ff4196fa0a1d6d96cd7f18a"
    end
    on_intel do
      url "https://github.com/keyorixhq/dashdiag/releases/download/v0.6.1/dsd-darwin-amd64"
      sha256 "53f92a29fd142e9c8e3485dbe773d2de811a128a17a7af4fb9cae718e18701f7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/keyorixhq/dashdiag/releases/download/v0.6.1/dsd-linux-arm64"
      sha256 "025d4892fcd5dc3497f842663abdca8f53bd3bed47eaff7fefee734c3bdd40f3"
    end
    on_intel do
      url "https://github.com/keyorixhq/dashdiag/releases/download/v0.6.1/dsd-linux-amd64"
      sha256 "ea7641e0cbf380a316cb2c6b0fcad54a3685c813f26d5ca445f92f487876efce"
    end
  end

  def install
    # Release assets are bare binaries named dsd-<os>-<arch>; install as "dsd".
    bin.install Dir["dsd-*"].first => "dsd"
  end

  test do
    assert_match "dsd version", shell_output("#{bin}/dsd --version")
  end
end
