package explain

import (
	"strings"
)

// Markdown renders every topic as a GitHub-flavored markdown reference — the
// source of truth for docs/CHECKS.md (kept in sync by markdown_test.go). It is a
// pure function of the topic registry: regenerate the doc with
// `dsd explain --markdown > docs/CHECKS.md`.
func Markdown() string {
	var b strings.Builder
	b.WriteString("<!-- Generated by `dsd explain --markdown`. Do not edit by hand. -->\n\n")
	b.WriteString("# DashDiag checks reference\n\n")
	b.WriteString("Every health check `dsd` runs, with what it looks at, why it matters, how the\n")
	b.WriteString("verdict is decided, and how to investigate and fix it. Run `dsd explain <topic>`\n")
	b.WriteString("for any of these, or `dsd explain --search <keyword>` to find one by content.\n\n")

	all := Topics()
	// Table of contents.
	for _, t := range all {
		b.WriteString("- [" + t.Title + "](#" + anchor(t.Title) + ")\n")
	}
	b.WriteString("\n")

	for _, t := range all {
		b.WriteString("## " + t.Title + " (`" + t.Key + "`)\n\n")
		b.WriteString("> " + t.Summary + "\n\n")
		b.WriteString("- **What it checks:** " + t.Checks + "\n")
		b.WriteString("- **Why it matters:** " + t.Matters + "\n")
		b.WriteString("- **How dsd decides:** " + t.Verdict + "\n")
		if len(t.Look) > 0 {
			b.WriteString("- **Investigate:** " + codeJoin(t.Look) + "\n")
		}
		if len(t.Fix) > 0 {
			b.WriteString("- **Fix:** " + strings.Join(t.Fix, "; ") + "\n")
		}
		if len(t.Aliases) > 0 {
			b.WriteString("- *Aliases:* " + strings.Join(t.Aliases, ", ") + "\n")
		}
		b.WriteString("\n")
	}
	return b.String()
}

// anchor turns a heading into its GitHub markdown anchor (lowercase, spaces→-,
// punctuation dropped). Good enough for the titles used here.
func anchor(title string) string {
	var s strings.Builder
	for _, r := range strings.ToLower(title) {
		switch {
		case (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9'):
			s.WriteRune(r)
		case r == ' ':
			s.WriteByte('-')
		}
	}
	return s.String()
}

// codeJoin wraps each command in backticks and joins with " · ".
func codeJoin(cmds []string) string {
	out := make([]string, len(cmds))
	for i, c := range cmds {
		out[i] = "`" + c + "`"
	}
	return strings.Join(out, " · ")
}
