package explain

// topics is the explain content registry. Keep entries accurate to the actual
// heuristics in internal/analysis — these are documentation of real behaviour, not
// aspirational. Add a topic by appending here; Lookup/Topics pick it up.
var topics = []Topic{
	{
		Key:     "cpu",
		Title:   "CPU load",
		Aliases: []string{"load", "cpu-load", "processor"},
		Summary: "Sustained CPU saturation relative to core count.",
		Checks:  "Load average from /proc/loadavg, normalized to the number of CPUs (load ÷ cores), plus per-core breakdown and steal/iowait in deep mode.",
		Matters: "Load sustained above core count means runnable work is queuing — requests wait, latency climbs. On VMs, high 'steal' means the hypervisor is starving this guest of physical CPU, which no amount of in-guest tuning fixes.",
		Verdict: "WARN at ~70% of capacity (load/cores), CRIT at ~90%. Brief spikes are normal; the 1-minute load average smooths them, so a verdict here means it has been busy, not momentarily blipped.",
		Look:    []string{"uptime", "top -b -n1 | head -20", "ps aux --sort=-%cpu | head", "mpstat -P ALL 1 3"},
		Fix:     []string{"identify the top consumer and whether it's expected", "on a VM, check steal: if high, the host is oversubscribed — raise it with your provider"},
	},
	{
		Key:     "memory",
		Title:   "Memory usage",
		Aliases: []string{"mem", "ram"},
		Summary: "Real memory pressure (not just 'used' — Linux uses free RAM for cache).",
		Checks:  "Used percentage from /proc/meminfo (MemTotal vs MemAvailable), slab size, and overcommit mode. 'Available' is what apps can actually get back, so cache doesn't count as pressure.",
		Matters: "True memory exhaustion triggers the OOM killer, which terminates processes unpredictably. Reading 'used' naively (counting cache) cries wolf; reading MemAvailable reflects real pressure.",
		Verdict: "WARN at 80% of MemAvailable consumed, CRIT at 95%. Overcommit is only flagged CRIT under strict accounting (vm.overcommit_memory=2), since the default heuristic mode legitimately overcommits.",
		Look:    []string{"free -h", "cat /proc/meminfo", "ps aux --sort=-%mem | head", "dmesg | grep -i oom"},
		Fix:     []string{"find the consumer; cap it with a cgroup/MemoryMax if it's a service", "add swap as a safety margin (not a substitute for RAM)"},
	},
	{
		Key:     "swap",
		Title:   "Swap usage & activity",
		Aliases: []string{"paging", "zram"},
		Summary: "Swap fill level and live paging rate — distinguishing disk thrash from zram.",
		Checks:  "Swap used % from /proc/swaps, and the live page-in/page-out rate sampled over 1 second from /proc/vmstat (pswpin/pswpout). zram devices are detected separately.",
		Matters: "Sustained paging to a disk-backed swap means RAM is exhausted and every faulted page costs a disk round-trip — the classic latency cliff. Paging to zram is compressed RAM at RAM speed, which is normal and cheap.",
		Verdict: "Usage WARN at 20%, CRIT at 60%. Activity: below 50 pages/s is background churn (silent); above that, disk-backed swap WARNs and >100 pages/s CRITs, while zram-backed paging is reported INFO ('compressed RAM, not disk thrash').",
		Look:    []string{"free -h", "swapon --show", "zramctl", "vmstat 1 5"},
		Fix:     []string{"if disk swap is thrashing, the real fix is more RAM or less working set", "tune vm.swappiness for the workload; consider zram for memory-constrained hosts"},
	},
	{
		Key:     "disk",
		Title:   "Filesystem capacity",
		Aliases: []string{"filesystem", "fs", "space", "df"},
		Summary: "Filesystem space and inode exhaustion.",
		Checks:  "Per-mount used % and inode used % from statfs, skipping network/virtual mounts. Stale NFS/CIFS mounts are detected without blocking.",
		Matters: "A full root filesystem breaks logging, package management, and most daemons. Inode exhaustion fills 'no space left' while df shows free bytes — a confusing outage if you only watch capacity.",
		Verdict: "WARN at 80% used, CRIT at 90% (same for inodes). Capacity verdicts are aligned across `dsd disk` and `dsd health` from one source so they never disagree.",
		Look:    []string{"df -h", "df -i", "du -xhd1 / | sort -h | tail", "find / -xdev -size +500M 2>/dev/null"},
		Fix:     []string{"clear the largest offenders (logs, caches, old kernels)", "for inode exhaustion, delete many small files (often a runaway temp/cache dir)"},
	},
	{
		Key:     "io",
		Title:   "Disk I/O",
		Aliases: []string{"iostat", "diskio", "disk-io"},
		Summary: "Block device saturation and latency.",
		Checks:  "Per-device utilization % and average wait, sampled from /proc/diskstats over 1 second (deep/standalone). Thresholds are drive-type aware (NVMe/SSD vs HDD).",
		Matters: "A saturated device backs up every process doing I/O — even healthy services stall waiting in D-state. 100% util on an NVMe is abnormal and usually points at a runaway process or btrfs maintenance.",
		Verdict: "Utilization and await thresholds vary by drive type (an HDD at 100% util is normal under load; an NVMe at 100% is not). 100% util adds a btrfs-cleaner note since that's a common benign-looking cause.",
		Look:    []string{"iostat -x 1 5", "iotop -ao", "ps -eo state,pid,cmd | grep '^D'"},
		Fix:     []string{"identify the I/O hog with iotop", "if btrfs, check whether btrfs-cleaner/scrub is running"},
	},
	{
		Key:     "drives",
		Title:   "Physical drive health (SMART)",
		Aliases: []string{"smart", "nvme", "ssd", "hdd", "wear"},
		Summary: "Drive-level failure prediction from SMART, not just filesystem space.",
		Checks:  "SMART overall health, NVMe percentage-used (endurance) and available-spare, media errors, reallocated/pending sectors on SATA, and power-on hours.",
		Matters: "SMART predicts impending failure before data is lost. Endurance (% used) and spare capacity are the real wear signals on SSD/NVMe; reallocated sectors are the canary on spinning disks.",
		Verdict: "SMART self-assessment FAIL is CRIT. NVMe wear ≥90% or spare at/below the drive's threshold is WARN/CRIT. Power-on hours is INFO only (age, not wear) — a healthy old enterprise drive is fine; never read hours as a failure signal.",
		Look:    []string{"smartctl -a /dev/sdX", "nvme smart-log /dev/nvmeXn1", "nvme list"},
		Fix:     []string{"a FAILING or high-wear drive: back up now and plan replacement", "reallocated/pending sectors climbing over time = replace"},
	},
	{
		Key:     "zfs",
		Title:   "ZFS pool health",
		Aliases: []string{"zpool", "pool"},
		Summary: "Pool state, scrub results, and vdev error counters.",
		Checks:  "Pool State (ONLINE/DEGRADED/FAULTED), capacity, fragmentation, scrub age, cumulative read/write/checksum vdev error counters, and unrepairable errors from the last scrub.",
		Matters: "A DEGRADED pool has lost redundancy — one more failure means data loss. Checksum errors caught and repaired indicate failing hardware (disk/RAM/cable) even when data is currently intact.",
		Verdict: "Not ONLINE → CRIT. Unrepairable scrub errors → CRIT (real corruption). The cumulative R/W/Cksum counters persist until `zpool clear` and include already-repaired errors, so on a healthy ONLINE pool with a clean scrub they are WARN ('repaired; investigate if recurring'), not a perpetual CRIT.",
		Look:    []string{"zpool status -v", "zpool list", "zpool events"},
		Fix:     []string{"DEGRADED: replace the faulted disk and resilver", "after fixing hardware and a clean scrub: zpool clear <pool> to reset counters"},
	},
	{
		Key:     "network",
		Title:   "Network reachability & TCP health",
		Aliases: []string{"net", "tcp", "gateway", "dns"},
		Summary: "Interface state, gateway/internet/DNS reachability, and TCP kernel counters.",
		Checks:  "Primary interface link, gateway and internet ping (TCP-fallback when ICMP is blocked), DNS resolution time, socket states (TIME_WAIT/CLOSE_WAIT), and TcpExt counters (SYN retransmits, listen overflows, retransmit failures).",
		Matters: "Reachability failures are the fastest path to a user-visible outage. CLOSE_WAIT buildup signals a connection leak in an app; listen-queue overflows mean a service's accept backlog is saturated and connections are dropped.",
		Verdict: "Down primary / total unreachability → CRIT; gateway-silent-but-internet-up → INFO (common with probe-blocking routers). The TcpExt counters are cumulative since boot, so they're rate-normalized against uptime — one old spike on a long-lived host is INFO, not a live alarm.",
		Look:    []string{"ip -br addr", "ss -s", "ss -tan state close-wait", "cat /proc/net/netstat | grep TcpExt"},
		Fix:     []string{"CLOSE_WAIT leak: find the app not closing sockets", "listen overflows: raise net.core.somaxconn and the app's backlog"},
	},
	{
		Key:     "systemd",
		Title:   "systemd unit health",
		Aliases: []string{"units", "services", "failed"},
		Summary: "Failed units and slow-boot offenders.",
		Checks:  "Units in the failed state (systemctl --failed), slow boot units from systemd-analyze, and journal health. Gated on systemd actually being the init system.",
		Matters: "A failed unit is a service that isn't doing its job — and often the root cause behind a higher-level symptom. Catching it by name points straight at the problem.",
		Verdict: "Any failed unit is surfaced (CRIT for the failure). DBus/journald checks are gated on systemd so non-systemd hosts (Alpine/OpenRC) don't get phantom failures.",
		Look:    []string{"systemctl --failed", "systemctl status <unit>", "journalctl -u <unit> -n 50", "systemd-analyze blame | head"},
		Fix:     []string{"read the unit's journal for the actual error", "after fixing, systemctl reset-failed <unit>"},
	},
	{
		Key:     "cve",
		Title:   "CVE / security advisories",
		Aliases: []string{"security-updates", "vulnerabilities", "patches", "kev"},
		Summary: "Pending security updates folded into health, escalated by CVSS and CISA KEV.",
		Checks:  "The package manager's pending security advisories (dnf/zypper expose real severity/CVSS; apt does not), cross-referenced against the local CISA Known-Exploited-Vulnerabilities catalog.",
		Matters: "Unpatched, actively-exploited CVEs are how most breaches start. KEV membership means it's being exploited in the wild right now — that outranks CVSS.",
		Verdict: "Any KEV match → CRIT. Otherwise CVSS ≥9.0 → CRIT, ≥7.0 → WARN (dnf/zypper). apt has no CVSS, so its name-inferred severities fold into a single honest WARN ('apt exposes no CVSS') rather than claiming a CVSS score it never measured.",
		Look:    []string{"dsd cve --all", "dnf updateinfo list security", "apt list --upgradable"},
		Fix:     []string{"patch KEV and critical advisories first", "dnf upgrade --security / apt upgrade the affected packages"},
	},
	{
		Key:     "hardening",
		Title:   "SSH & host hardening",
		Aliases: []string{"ssh", "sshd"},
		Summary: "SSH daemon policy and basic account hygiene.",
		Checks:  "Effective sshd config (sshd -T): password auth, root login, weak ciphers/MACs/KEX, plus empty passwords and account expiry. Match-block overrides are not mistaken for global policy.",
		Matters: "SSH is the front door. Password auth and permitted root login are the two settings most often abused for brute-force entry; weak MACs/ciphers expose sessions to downgrade attacks.",
		Verdict: "Password auth enabled, root login permitted, or weak crypto each WARN. These are policy recommendations, not failures — a deliberately password-auth host is a choice, surfaced so it's a choice and not an oversight.",
		Look:    []string{"sshd -T | grep -Ei 'passwordauth|permitroot|macs|ciphers'", "passwd -Sa | awk '$2==\"NP\"'"},
		Fix:     []string{"prefer key-based auth: set PasswordAuthentication no", "set PermitRootLogin prohibit-password (or no)"},
	},
	{
		Key:     "clock",
		Title:   "Time synchronization",
		Aliases: []string{"ntp", "time", "chrony"},
		Summary: "Whether the system clock is disciplined by NTP.",
		Checks:  "Synchronization state from timedatectl/chrony, and whether the RTC is in local time. Drift and sync source are reported.",
		Matters: "Clock skew breaks TLS validation, Kerberos/AD auth, distributed databases, log correlation, and certificate checks. It causes failures that look like everything-but-the-clock.",
		Verdict: "Not synchronized → CRIT, unless the RTC-in-local-time case (common dual-boot-with-Windows) is detected — then WARN, since NTP may actually be fine and the kernel is just reporting unsync.",
		Look:    []string{"timedatectl status", "chronyc tracking", "systemctl status chronyd systemd-timesyncd"},
		Fix:     []string{"enable an NTP client (chrony/systemd-timesyncd)", "dual-boot RTC: timedatectl set-local-rtc 0"},
	},
}
