package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"

	"github.com/keyorixhq/dashdiag/internal/output"
	"github.com/keyorixhq/dashdiag/internal/tips"
	"github.com/keyorixhq/dashdiag/internal/tui"
)

func init() {
	rootCmd.AddCommand(hookCmd)
	hookCmd.AddCommand(hookInstallCmd)
	hookInstallCmd.Flags().Bool("dry-run", false, "show what would be written without writing")
}

var hookCmd = &cobra.Command{
	Use:   "hook",
	Short: "Manage shell and CI hooks",
}

var hookInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install DashDiag hooks for login, git, CI, and more",
	RunE:  runHookInstall,
}

const sshSnippet = `
# DashDiag health check on login (remove to disable)
which dsd &>/dev/null && dsd health --plain --compact 2>/dev/null || true
`

const preDeployScript = `#!/bin/bash
# DashDiag pre-deploy health check (auto-generated by dsd hook install)
set -e
echo "→ Running health check before deploy..."
dsd health || { echo "❌ Health check failed. Deploy aborted."; exit 1; }
echo "✅ Health check passed."
`

const gitPrePushHook = `#!/bin/bash
# DashDiag pre-push health check (auto-generated by dsd hook install)
which dsd &>/dev/null && dsd health --plain --compact 2>/dev/null || true
`

const systemdTimer = `[Unit]
Description=DashDiag periodic health check timer

[Timer]
OnBootSec=2min
OnUnitActiveSec=1h
Persistent=true

[Install]
WantedBy=timers.target
`

const systemdService = `[Unit]
Description=DashDiag health check

[Service]
Type=oneshot
ExecStart=/usr/local/bin/dsd health --plain
StandardOutput=journal
StandardError=journal
`

const githubWorkflow = `name: DashDiag Health Check
on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */6 * * *'
jobs:
  health:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install DashDiag
        run: curl -sSL https://dashdiag.sh/install.sh | bash
      - name: System health check
        run: dsd health
`

var hookOptions = []string{
	"SSH login (append to ~/.bashrc or ~/.zshrc)",
	"Pre-deploy script (generate scripts/check-health.sh)",
	"Git pre-push hook (.git/hooks/pre-push)",
	"systemd timer (/etc/systemd/system/dsd-health.timer)",
	"GitHub Actions (.github/workflows/dsd-health.yml)",
	"Show commands only (no files written)",
}

func runHookInstall(cmd *cobra.Command, _ []string) error {
	dryRun, _ := cmd.Flags().GetBool("dry-run")
	plain, _ := cmd.Flags().GetBool("plain")
	mode := output.DetectMode(plain, false, "")

	if dryRun {
		fmt.Println("DRY RUN — no files will be written")
		fmt.Println()
	}

	chosen, err := tui.RunMultiSelect("Select hooks to install:", hookOptions)
	if err != nil || len(chosen) == 0 {
		fmt.Println("No hooks selected.")
		return nil
	}

	installed := false
	for _, opt := range chosen {
		switch {
		case strings.HasPrefix(opt, "SSH login"):
			installed = true
			installSSHHook(dryRun)
		case strings.HasPrefix(opt, "Pre-deploy"):
			installed = true
			installPreDeploy(dryRun)
		case strings.HasPrefix(opt, "Git pre-push"):
			installed = true
			installGitHook(dryRun)
		case strings.HasPrefix(opt, "systemd"):
			installed = true
			installSystemdTimer(dryRun)
		case strings.HasPrefix(opt, "GitHub Actions"):
			installed = true
			installGitHubActions(dryRun)
		case strings.HasPrefix(opt, "Show commands"):
			printHookCommands(mode)
		}
	}

	if installed && !dryRun {
		state, _ := tips.LoadState()
		if state != nil {
			state.HookInstalled = true
			_ = state.Save()
		}
		fmt.Println("\n✅ Hooks installed. Run dsd health to verify.")
	}
	return nil
}

func shellRCPath() string {
	home, _ := os.UserHomeDir()
	if _, err := os.Stat(filepath.Join(home, ".zshrc")); err == nil {
		return filepath.Join(home, ".zshrc")
	}
	return filepath.Join(home, ".bashrc")
}

func installSSHHook(dryRun bool) {
	path := shellRCPath()
	if dryRun {
		fmt.Printf("Would modify %s:\n", path)
		for line := range strings.SplitSeq(strings.TrimSpace(sshSnippet), "\n") {
			fmt.Printf("  + %s\n", line)
		}
		fmt.Println()
		return
	}
	f, err := os.OpenFile(filepath.Clean(path), os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0644) // #nosec G302 G304 -- shell RC files (.bashrc, .zshrc) must be world-readable; path comes from internal home-dir detection, not user input
	if err != nil {
		fmt.Fprintf(os.Stderr, "error: could not write %s: %v\n", path, err)
		return
	}
	defer func() { _ = f.Close() }()
	_, _ = f.WriteString(sshSnippet)
	fmt.Printf("✅ SSH hook added to %s\n", path)
}

func installPreDeploy(dryRun bool) {
	path := "scripts/check-health.sh"
	if dryRun {
		fmt.Printf("Would create %s\n\n", path)
		return
	}
	if err := os.MkdirAll("scripts", 0750); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return
	}
	// 0755: pre-deploy script must be executable
	if err := os.WriteFile(path, []byte(preDeployScript), 0755); err != nil { // #nosec G306 -- pre-deploy script must be executable
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return
	}
	fmt.Printf("✅ Pre-deploy script created: %s\n", path)
}

func installGitHook(dryRun bool) {
	path := ".git/hooks/pre-push"
	if dryRun {
		fmt.Printf("Would create %s\n\n", path)
		return
	}
	if _, err := os.Stat(".git"); os.IsNotExist(err) {
		fmt.Fprintln(os.Stderr, "error: not a git repository")
		return
	}
	if err := os.MkdirAll(".git/hooks", 0750); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return
	}
	// 0755: git hook must be executable
	if err := os.WriteFile(path, []byte(gitPrePushHook), 0755); err != nil { // #nosec G306 -- git hook must be executable
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return
	}
	fmt.Printf("✅ Git pre-push hook installed: %s\n", path)
}

func installSystemdTimer(dryRun bool) {
	timerPath := "/etc/systemd/system/dsd-health.timer"
	svcPath := "/etc/systemd/system/dsd-health.service"
	if dryRun {
		fmt.Printf("Would create %s (requires root)\n", timerPath)
		fmt.Printf("Would create %s (requires root)\n\n", svcPath)
		return
	}
	// 0644: systemd unit files in /etc/systemd/system/ are conventionally world-readable
	if err := os.WriteFile(timerPath, []byte(systemdTimer), 0644); err != nil { // #nosec G306 -- systemd unit files in /etc/systemd/system/ are world-readable by convention
		fmt.Fprintf(os.Stderr, "error (may need sudo): %v\n", err)
		fmt.Fprintln(os.Stderr, "  Run: sudo dsd hook install")
		return
	}
	if err := os.WriteFile(svcPath, []byte(systemdService), 0644); err != nil { // #nosec G306 -- systemd unit files in /etc/systemd/system/ are world-readable by convention
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
	}
	fmt.Printf("✅ Systemd timer installed. Enable with: sudo systemctl enable --now dsd-health.timer\n")
}

func installGitHubActions(dryRun bool) {
	path := ".github/workflows/dsd-health.yml"
	if dryRun {
		fmt.Printf("Would create %s\n\n", path)
		return
	}
	if err := os.MkdirAll(".github/workflows", 0750); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return
	}
	if err := os.WriteFile(path, []byte(githubWorkflow), 0644); err != nil { // #nosec G306 -- CI workflow files are world-readable by convention
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		return
	}
	fmt.Printf("✅ GitHub Actions workflow created: %s\n", path)
}

func printHookCommands(_ output.OutputMode) {
	fmt.Println("\n── Hook commands ──────────────────────────────")
	fmt.Println("SSH login:  Add to ~/.zshrc or ~/.bashrc:")
	fmt.Printf("  %s\n", strings.TrimSpace(sshSnippet))
	fmt.Println()
	fmt.Println("Pre-deploy: dsd health || exit 1")
	fmt.Println("Git hook:   echo 'dsd health --plain --compact' > .git/hooks/pre-push && chmod +x .git/hooks/pre-push")
	fmt.Println("CI:         Add 'dsd health' step to your pipeline")
	fmt.Println("────────────────────────────────────────────────")
}
