package cmd

// share_test.go — unit tests for `dsd share`. Most tests call the package
// functions directly (isBundlePath, shareFromSnapshotFile, renderShareArtifact,
// writeShareArtifact, writeShareJSON) rather than going through cobra/rootCmd
// dispatch, mirroring cmd/root_test.go's newBareRootPreRunCmd pattern: a bare
// *cobra.Command with only the flags a given function actually reads.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"

	"github.com/keyorixhq/dashdiag/internal/baseline"
	"github.com/keyorixhq/dashdiag/internal/platform"
	"github.com/keyorixhq/dashdiag/internal/share"
)

// newBareShareCmd returns a *cobra.Command carrying every flag runShare and
// its helpers read (dsd share's own local flags plus the two root persistent
// flags they also consult) — bare, so tests don't depend on rootCmd's shared
// package-level state.
func newBareShareCmd() *cobra.Command {
	c := &cobra.Command{}
	f := c.Flags()
	f.String("format", "md", "")
	f.String("from", "", "")
	f.Bool("last", false, "")
	f.Bool("stdout", false, "")
	f.Bool("no-redact", false, "")
	f.Bool("keep-hostnames", false, "")
	f.Bool("keep-ips", false, "")
	f.Bool("deep", false, "")
	f.Bool("cve", false, "")
	f.Bool("json", false, "")
	f.String("out", "", "")
	return c
}

func TestIsBundlePath(t *testing.T) {
	t.Parallel()
	cases := map[string]bool{
		"bundle.tar.gz":     true,
		"host-20260101.tgz": true,
		"snapshot.json":     false,
		"bundle.tar.gz.txt": false,
		"":                  false,
	}
	for path, want := range cases {
		if got := isBundlePath(path); got != want {
			t.Errorf("isBundlePath(%q) = %v, want %v", path, got, want)
		}
	}
}

func TestDefaultShareFilename(t *testing.T) {
	t.Parallel()
	ts := time.Date(2026, 9, 23, 15, 4, 5, 0, time.UTC)
	got := defaultShareFilename("web-prod/01", ts, "md")
	want := "dsd-share-web-prod_01-20260923-150405.md"
	if got != want {
		t.Errorf("defaultShareFilename() = %q, want %q", got, want)
	}
}

func TestAddShareUTM(t *testing.T) {
	t.Parallel()
	md := "*Generated by [DashDiag](https://github.com/keyorixhq/dashdiag) dev — [dashdiag.sh](https://dashdiag.sh)*"
	gotMD := addShareUTM(md, false)
	if !strings.Contains(gotMD, "(https://dashdiag.sh/?src=share)") {
		t.Errorf("addShareUTM(markdown) missing tagged link: %q", gotMD)
	}

	html := `<a href="https://dashdiag.sh">dashdiag.sh</a>`
	gotHTML := addShareUTM(html, true)
	if !strings.Contains(gotHTML, `href="https://dashdiag.sh/?src=share"`) {
		t.Errorf("addShareUTM(html) missing tagged link: %q", gotHTML)
	}
}

// buildTestSnapshotFile writes a minimal baseline.Snapshot JSON file (the
// shape `dsd health --out snapshot.json` or baseline.SaveBaseline produces)
// and returns its path.
func buildTestSnapshotFile(t *testing.T, hostname string) string {
	t.Helper()
	snap := baseline.Snapshot{
		Hostname:  hostname,
		Timestamp: time.Date(2026, 9, 23, 12, 0, 0, 0, time.UTC),
		Version:   "v9.9.9",
		Checks: []baseline.CheckResult{
			{Name: "CPU Load", Status: "OK", Value: "3%"},
			{Name: "Docker", Status: "CRIT", Value: "container crash looping"},
		},
	}
	data, err := json.Marshal(snap)
	if err != nil {
		t.Fatalf("marshalling test snapshot: %v", err)
	}
	path := filepath.Join(t.TempDir(), "snapshot.json")
	if err := os.WriteFile(path, data, 0o600); err != nil {
		t.Fatalf("writing test snapshot: %v", err)
	}
	return path
}

// TestShareFromSnapshotFile is not t.Parallel(): shareFromSnapshotFile
// mutates the process-global platform identity override (platform.SetIdentity),
// which every other test in this file that touches identity also relies on —
// see dockerHostMeltdownShareSource's doc comment.
func TestShareFromSnapshotFile(t *testing.T) {
	path := buildTestSnapshotFile(t, "web-prod-01")

	src, err := shareFromSnapshotFile(path)
	if err != nil {
		t.Fatalf("shareFromSnapshotFile: %v", err)
	}
	defer src.restore()

	if src.snap.Hostname != "web-prod-01" {
		t.Errorf("snap.Hostname = %q, want web-prod-01", src.snap.Hostname)
	}
	if len(src.results) != 2 {
		t.Errorf("len(results) = %d, want 2", len(src.results))
	}
	if len(src.insights) != 1 || src.insights[0].Check != "Docker" || src.insights[0].Level != "CRIT" {
		t.Errorf("expected exactly one reconstructed CRIT insight for Docker, got %+v", src.insights)
	}
}

// TestRenderShareArtifact_AllFormats exercises every --format value against
// the docker-host-meltdown fixture (fixtures/docker-host-meltdown.yaml), via
// the same mockFixtureResults path `dsd mock`/`dsd demo` use. Not t.Parallel()
// at any level — dockerHostMeltdownShareSource mutates the process-global
// platform identity override.
func TestRenderShareArtifact_AllFormats(t *testing.T) {
	src := dockerHostMeltdownShareSource(t)

	t.Run("md", func(t *testing.T) {
		out, counts, err := renderShareArtifact("md", src, share.RedactOptions{})
		if err != nil {
			t.Fatalf("renderShareArtifact(md): %v", err)
		}
		if !strings.Contains(out, "# DashDiag Health Report") {
			t.Errorf("expected markdown report header, got:\n%s", out)
		}
		if !strings.Contains(out, "https://dashdiag.sh/checks/docker") {
			t.Errorf("expected a check-ID link to the docker catalog page, got:\n%s", out)
		}
		if !strings.Contains(out, "https://dashdiag.sh/?src=share") {
			t.Errorf("expected the footer link tagged with ?src=share, got:\n%s", out)
		}
		if strings.Contains(out, "docker-prod-01") {
			t.Errorf("expected the fixture hostname to be redacted, got:\n%s", out)
		}
		if counts.Total() == 0 {
			t.Errorf("expected nonzero redaction counts (hostname at least), got %v", counts)
		}
		if !strings.Contains(out, "**Top catch:**") {
			t.Errorf("expected a Top catch line, got:\n%s", out)
		}
	})

	t.Run("html", func(t *testing.T) {
		out, _, err := renderShareArtifact("html", src, share.RedactOptions{})
		if err != nil {
			t.Fatalf("renderShareArtifact(html): %v", err)
		}
		if !strings.Contains(out, "<!DOCTYPE html>") {
			t.Errorf("expected an HTML document, got:\n%s", out)
		}
		if !strings.Contains(out, "https://dashdiag.sh/checks/docker") {
			t.Errorf("expected a check-ID link to the docker catalog page, got:\n%s", out)
		}
		if !strings.Contains(out, `href="https://dashdiag.sh/?src=share"`) {
			t.Errorf("expected the footer link tagged with ?src=share, got:\n%s", out)
		}
		if !strings.Contains(out, "Top catch:") {
			t.Errorf("expected a Top catch line, got:\n%s", out)
		}
	})

	t.Run("text", func(t *testing.T) {
		out, _, err := renderShareArtifact("text", src, share.RedactOptions{})
		if err != nil {
			t.Fatalf("renderShareArtifact(text): %v", err)
		}
		if !strings.Contains(out, "https://dashdiag.sh/checks/docker") {
			t.Errorf("expected a check-ID link to the docker catalog page, got:\n%s", out)
		}
		if n := len(strings.Split(strings.TrimRight(out, "\n"), "\n")); n > 40 {
			t.Errorf("text format is %d lines, want <= 40:\n%s", n, out)
		}
		// Top catch must be the line immediately under Verdict.
		lines := strings.Split(out, "\n")
		verdictIdx := -1
		for i, l := range lines {
			if strings.HasPrefix(l, "Verdict:") {
				verdictIdx = i
				break
			}
		}
		if verdictIdx < 0 || verdictIdx+1 >= len(lines) || !strings.HasPrefix(lines[verdictIdx+1], "Top catch:") {
			t.Errorf("expected \"Top catch:\" on the line right after Verdict, got:\n%s", out)
		}
	})

	t.Run("blob", func(t *testing.T) {
		out, _, err := renderShareArtifact("blob", src, share.RedactOptions{})
		if err != nil {
			t.Fatalf("renderShareArtifact(blob): %v", err)
		}
		decoded, err := share.Decode(out)
		if err != nil {
			t.Fatalf("decoding blob output: %v", err)
		}
		if strings.Contains(string(decoded), "docker-prod-01") {
			t.Errorf("expected the fixture hostname to be redacted inside the blob, got:\n%s", decoded)
		}
	})

	t.Run("unknown format", func(t *testing.T) {
		if _, _, err := renderShareArtifact("pdf", src, share.RedactOptions{}); err == nil {
			t.Fatal("expected an error for an unknown format, got nil")
		}
	})
}

func TestRenderShareArtifact_NoRedactKeepsHostname(t *testing.T) {
	src := dockerHostMeltdownShareSource(t)
	out, counts, err := renderShareArtifact("text", src, share.RedactOptions{Disabled: true})
	if err != nil {
		t.Fatalf("renderShareArtifact: %v", err)
	}
	if !strings.Contains(out, "docker-prod-01") {
		t.Errorf("expected --no-redact to keep the hostname, got:\n%s", out)
	}
	if len(counts) != 0 {
		t.Errorf("expected zero redaction counts with Disabled, got %v", counts)
	}
}

func TestRenderShareArtifact_KeepHostnames(t *testing.T) {
	src := dockerHostMeltdownShareSource(t)
	out, counts, err := renderShareArtifact("text", src, share.RedactOptions{KeepHostnames: true})
	if err != nil {
		t.Fatalf("renderShareArtifact: %v", err)
	}
	if !strings.Contains(out, "docker-prod-01") {
		t.Errorf("expected --keep-hostnames to keep the hostname, got:\n%s", out)
	}
	if counts["hostnames"] != 0 {
		t.Errorf("expected zero hostname redactions, got %d", counts["hostnames"])
	}
}

// dockerHostMeltdownShareSource builds a shareSource from
// fixtures/docker-host-meltdown.yaml via the same mockFixtureResults path
// `dsd mock`/`dsd demo` render through.
func dockerHostMeltdownShareSource(t *testing.T) *shareSource {
	t.Helper()
	raw, err := os.ReadFile("../fixtures/docker-host-meltdown.yaml")
	if err != nil {
		t.Fatalf("reading fixture: %v", err)
	}
	var fix MockFixture
	if err := yaml.Unmarshal(raw, &fix); err != nil {
		t.Fatalf("parsing fixture: %v", err)
	}
	results, insights := mockFixtureResults(fix)
	snap := baseline.BuildSnapshot(results, insights)
	snap.Hostname = fix.Host
	// render.BuildJSONOutput (used by writeShareJSON) reads platform.Hostname(),
	// not snap.Hostname directly — override it the same way shareFromBundle/
	// shareFromSnapshotFile do in the real flow, so a test built from a fixture
	// (rather than a live/replayed run) sees the same invariant.
	restore := platform.SetIdentity(fix.Host, fix.OS)
	t.Cleanup(restore)
	return &shareSource{
		results: results, insights: insights, snap: snap,
		elapsed: 3 * time.Second, osLabel: fix.OS,
	}
}

func TestWriteShareArtifact_SymlinkRefused(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	ts := time.Date(2026, 9, 23, 12, 0, 0, 0, time.UTC)
	src := &shareSource{snap: &baseline.Snapshot{Hostname: "victim-host", Timestamp: ts}}
	target := filepath.Join(dir, "victim.txt")
	if err := os.WriteFile(target, []byte("do not touch"), 0o600); err != nil {
		t.Fatal(err)
	}
	autoPath := defaultShareFilename(src.snap.Hostname, src.snap.Timestamp, "md")
	if err := os.Symlink(target, autoPath); err != nil {
		t.Fatal(err)
	}

	cmd := newBareShareCmd()
	err := writeShareArtifact(cmd, src, "report body", "md", false, share.Counts{})
	if err == nil {
		t.Fatal("expected writeShareArtifact to refuse writing through a symlink")
	}

	data, rerr := os.ReadFile(target)
	if rerr != nil {
		t.Fatal(rerr)
	}
	if string(data) != "do not touch" {
		t.Errorf("symlink target was modified: got %q", data)
	}
}

func TestWriteShareArtifact_DefaultWritesFile(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)

	ts := time.Date(2026, 9, 23, 12, 0, 0, 0, time.UTC)
	src := &shareSource{snap: &baseline.Snapshot{Hostname: "web-prod-01", Timestamp: ts}}

	cmd := newBareShareCmd()
	if err := writeShareArtifact(cmd, src, "report body", "md", false, share.Counts{"ips": 1}); err != nil {
		t.Fatalf("writeShareArtifact: %v", err)
	}

	autoPath := defaultShareFilename(src.snap.Hostname, src.snap.Timestamp, "md")
	data, err := os.ReadFile(autoPath)
	if err != nil {
		t.Fatalf("reading auto-named output: %v", err)
	}
	if string(data) != "report body" {
		t.Errorf("output file content = %q, want %q", data, "report body")
	}
	info, err := os.Stat(autoPath)
	if err != nil {
		t.Fatal(err)
	}
	if info.Mode().Perm() != 0o600 {
		t.Errorf("output file mode = %v, want 0600", info.Mode().Perm())
	}
}

func TestWriteShareJSON_AdditiveFields(t *testing.T) {
	src := dockerHostMeltdownShareSource(t)

	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	werr := writeShareJSON(src, share.RedactOptions{})
	_ = w.Close()
	os.Stdout = old
	if werr != nil {
		t.Fatalf("writeShareJSON: %v", werr)
	}

	var out struct {
		Hostname   string         `json:"hostname"`
		Verdict    string         `json:"verdict"`
		Redacted   bool           `json:"redacted"`
		Redactions map[string]int `json:"redactions"`
	}
	dec := json.NewDecoder(r)
	if err := dec.Decode(&out); err != nil {
		t.Fatalf("decoding --json output: %v", err)
	}
	if !out.Redacted {
		t.Error("expected redacted=true")
	}
	if out.Hostname == "docker-prod-01" {
		t.Error("expected hostname redacted in --json output")
	}
	if len(out.Redactions) == 0 {
		t.Error("expected nonzero redactions map")
	}
	if out.Verdict != "CRIT" {
		t.Errorf("verdict = %q, want CRIT (fixture has a Docker CRIT)", out.Verdict)
	}
}

func TestRunShare_FromSnapshotEndToEnd(t *testing.T) {
	dir := t.TempDir()
	t.Chdir(dir)
	path := buildTestSnapshotFile(t, "web-prod-01")

	cmd := newBareShareCmd()
	_ = cmd.Flags().Set("from", path)
	_ = cmd.Flags().Set("format", "text")
	_ = cmd.Flags().Set("stdout", "true")

	old := os.Stdout
	r, w, err := os.Pipe()
	if err != nil {
		t.Fatal(err)
	}
	os.Stdout = w
	runErr := runShare(cmd, nil)
	_ = w.Close()
	os.Stdout = old
	if runErr != nil {
		t.Fatalf("runShare: %v", runErr)
	}

	buf := make([]byte, 8192)
	n, _ := r.Read(buf)
	out := string(buf[:n])
	if !strings.Contains(out, "[CRIT]") {
		t.Errorf("expected the reconstructed CRIT finding in text output, got:\n%s", out)
	}
	if strings.Contains(out, "web-prod-01") {
		t.Errorf("expected the hostname redacted by default, got:\n%s", out)
	}
}

func TestRunShare_UnknownFormat(t *testing.T) {
	t.Parallel()
	cmd := newBareShareCmd()
	_ = cmd.Flags().Set("format", "pdf")
	if err := runShare(cmd, nil); err == nil {
		t.Fatal("expected an error for an unknown --format, got nil")
	}
}
