//go:build linux

package cvedata

import (
	"context"
	"os/exec"
	"path/filepath"
	"testing"
)

// rpmUnavailable reports whether the "rpm" binary is absent from PATH in the
// current test environment. The RPM-backed scanners (RHEL/SUSE) shell out to
// it, and this repo's containers/CI runners are Debian-family and don't ship
// it — so QueryInstalledRPM deterministically errors here. Guarding on
// exec.LookPath (rather than assuming absence) keeps the test honest on a
// host that DOES have rpm installed, where it would skip instead of asserting
// a false expectation.
func rpmUnavailable(t *testing.T) {
	t.Helper()
	if _, err := exec.LookPath("rpm"); err == nil {
		t.Skip("rpm is available on this host — the guaranteed-failure path this test checks does not apply")
	}
}

// ── scanRHELOVALPackages / ScanOVALPackages (RHEL branch) ──────────────────

func TestScanRHELOVALPackages_ParseError(t *testing.T) {
	t.Parallel()
	if _, err := scanRHELOVALPackages(context.Background(), filepath.Join(t.TempDir(), "missing.xml")); err == nil {
		t.Error("expected error for missing OVAL file")
	}
}

func TestScanRHELOVALPackages_QueryInstalledRPMFails(t *testing.T) {
	t.Parallel()
	rpmUnavailable(t)
	path := writeFixture(t, "rhel.xml", rhelOVAL)
	if _, err := scanRHELOVALPackages(context.Background(), path); err == nil {
		t.Error("expected error when rpm is unavailable to query installed packages")
	}
}

// sniffableRHELOVAL carries a "redhat.com" content marker so sniffOVALVendor
// routes it to the RHEL scanner purely from content, even under a neutral
// filename — distinct from TestScanOVALPackages_DispatchFallsBackToRHEL
// below, which exercises the fallback-when-inconclusive path instead. The
// XML declaration must stay first, so the marker lives in a comment after it.
const sniffableRHELOVAL = `<?xml version="1.0"?>
<!-- source: https://access.redhat.com/security/data/oval/ -->
<oval_definitions>
  <definitions>
    <definition class="vulnerability">
      <metadata>
        <reference source="CVE" ref_id="CVE-2030-0002"/>
        <advisory>
          <severity>Critical</severity>
          <cve cvss3="9.5/CVSS:3.1/AV:N" impact="critical">CVE-2030-0002</cve>
          <affected>
            <resolution state="Affected"><component>testpkg</component></resolution>
          </affected>
        </advisory>
      </metadata>
    </definition>
  </definitions>
</oval_definitions>`

func TestScanOVALPackages_DispatchToRHELOnContentSniff(t *testing.T) {
	t.Parallel()
	rpmUnavailable(t)
	path := writeFixture(t, "feed.xml", sniffableRHELOVAL) // neutral filename, content decides
	if _, err := ScanOVALPackages(context.Background(), path); err == nil {
		t.Error("expected the RHEL dispatch path to surface the rpm-unavailable error")
	}
}

// ── ScanSUSEOVALPackages / ScanOVALPackages (SUSE branch) ───────────────────

func TestScanSUSEOVALPackages_LoadError(t *testing.T) {
	t.Parallel()
	if _, err := ScanSUSEOVALPackages(context.Background(), filepath.Join(t.TempDir(), "missing.xml")); err == nil {
		t.Error("expected error for missing OVAL file")
	}
}

func TestScanSUSEOVALPackages_QueryInstalledRPMFails(t *testing.T) {
	t.Parallel()
	rpmUnavailable(t)
	path := writeFixture(t, "suse.xml", suseOVAL)
	if _, err := ScanSUSEOVALPackages(context.Background(), path); err == nil {
		t.Error("expected error when rpm is unavailable to query installed packages")
	}
}

func TestScanOVALPackages_DispatchToSUSEByFilename(t *testing.T) {
	t.Parallel()
	rpmUnavailable(t)
	// Content doesn't sniff to any vendor, so dispatch falls back to the
	// filename hint — "sles" in the name routes to the SUSE scanner.
	path := writeFixture(t, "sles15-custom.xml", suseOVAL)
	if _, err := ScanOVALPackages(context.Background(), path); err == nil {
		t.Error("expected the SUSE dispatch path (by filename) to surface the rpm-unavailable error")
	}
}

func TestScanOVALPackages_DispatchFallsBackToRHEL(t *testing.T) {
	t.Parallel()
	rpmUnavailable(t)
	// Content doesn't sniff, filename doesn't match ubuntu/suse hints either
	// -> falls through to the RHEL scanner as the final default.
	path := writeFixture(t, "neutral-name.xml", rhelOVAL)
	if _, err := ScanOVALPackages(context.Background(), path); err == nil {
		t.Error("expected the default RHEL dispatch path to surface the rpm-unavailable error")
	}
}

// ── ScanOVALPackages (Ubuntu branch, real dpkg-query) ────────────────────────

// suseSniffableUbuntuOVAL carries a content marker ("canonical") that
// sniffOVALVendor recognises, so ScanOVALPackages routes to
// ScanUbuntuOVALPackages regardless of the file's name.
const sniffableUbuntuOVAL = `<?xml version="1.0"?>
<!-- generated by canonical -->
<oval_definitions>
  <definitions>
    <definition class="vulnerability">
      <metadata>
        <reference source="CVE" ref_id="CVE-2030-0001"/>
        <advisory><severity>high</severity></advisory>
      </metadata>
      <criteria>
        <criterion comment="bash package in noble is affected and may need fixing."/>
      </criteria>
    </definition>
  </definitions>
</oval_definitions>`

// TestScanOVALPackages_DispatchToUbuntuAndFindsRealPackage exercises the full
// Ubuntu dispatch path against the REAL system dpkg database (dpkg-query is
// present in this repo's containers, unlike rpm). "bash" is present on any
// Debian/Ubuntu base image, so this is a deterministic pass, not a flaky
// dependency on exact package contents.
func TestScanOVALPackages_DispatchToUbuntuAndFindsRealPackage(t *testing.T) {
	t.Parallel()
	if _, err := exec.LookPath("dpkg-query"); err != nil {
		t.Skip("dpkg-query not available on this host")
	}
	path := writeFixture(t, "feed.xml", sniffableUbuntuOVAL)
	results, err := ScanOVALPackages(context.Background(), path)
	if err != nil {
		t.Fatalf("ScanOVALPackages: %v", err)
	}
	if len(results) != 1 || results[0].CVEID != "CVE-2030-0001" {
		t.Fatalf("results = %+v, want 1 hit for CVE-2030-0001 (bash is always installed)", results)
	}
	if len(results[0].Installed) != 1 || results[0].Installed[0] != "bash" {
		t.Errorf("Installed = %v, want [bash]", results[0].Installed)
	}
}

// ── CheckCVEFromOVAL (found path, RPM query) ────────────────────────────────

func TestCheckCVEFromOVAL_FoundButRPMQueryFails(t *testing.T) {
	t.Parallel()
	rpmUnavailable(t)
	path := writeFixture(t, "suse.xml", suseOVAL)
	res, err := CheckCVEFromOVAL(context.Background(), path, "CVE-2025-0001")
	if err == nil {
		t.Fatal("expected error once the CVE is found and rpm querying fails")
	}
	// The definition-match fields are still populated before the query fails.
	if res == nil || !res.Found || res.Summary == "" {
		t.Errorf("result = %+v, want Found=true with Summary populated despite the query error", res)
	}
}
