package cvedata

import (
	"compress/bzip2"
	"compress/gzip"
	"encoding/json"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// DetectDistroID reads the distro ID from /etc/os-release.
// Returns "" on non-Linux or when the file is absent.
func DetectDistroID() string {
	data, err := os.ReadFile("/etc/os-release") // #nosec G304
	if err != nil {
		return ""
	}
	for _, line := range strings.Split(string(data), "\n") {
		if strings.HasPrefix(line, "ID=") {
			return strings.Trim(strings.TrimPrefix(line, "ID="), `"`)
		}
	}
	return ""
}

// StandardOVALPaths returns the candidate locations dsd looks for OVAL files,
// in priority order. Admins place OVAL files here; dsd discovers them automatically.
//
// OVAL files can be downloaded from:
//
//	SLES/openSUSE: https://ftp.suse.com/pub/projects/security/oval/
//	RHEL/Rocky:    https://www.redhat.com/security/data/oval/
func StandardOVALPaths() []string {
	// System-wide first, then user-local
	paths := []string{
		"/var/lib/dsd/oval",
		"/etc/dsd/oval",
	}
	if home, err := os.UserHomeDir(); err == nil {
		paths = append(paths, filepath.Join(home, ".local", "share", "dsd", "oval"))
		paths = append(paths, filepath.Join(home, ".dsd", "oval"))
	}
	return paths
}

// FindOVALFile searches standard paths for an OVAL file matching the current distro.
// Returns the first match found, or "" if none.
func FindOVALFile(distroID string) string {
	// Map distro IDs to candidate filenames
	candidates := ovalFileCandidates(distroID)

	for _, dir := range StandardOVALPaths() {
		for _, name := range candidates {
			path := filepath.Join(dir, name)
			if _, err := os.Stat(path); err == nil {
				return path
			}
		}
		// Also accept any .xml.bz2 or .xml file in the directory
		entries, err := os.ReadDir(dir)
		if err != nil {
			continue
		}
		for _, e := range entries {
			if !e.IsDir() && (strings.HasSuffix(e.Name(), ".xml.bz2") ||
				strings.HasSuffix(e.Name(), ".xml")) {
				return filepath.Join(dir, e.Name())
			}
		}
	}
	return ""
}

func ovalFileCandidates(distroID string) []string {
	lower := strings.ToLower(distroID)
	switch {
	case strings.Contains(lower, "sles") || strings.Contains(lower, "suse enterprise"):
		return []string{
			"suse.linux.enterprise.server.16.xml.bz2",
			"suse.linux.enterprise.server.15.xml.bz2",
			"sles16.xml.bz2", "sles15.xml.bz2",
		}
	case strings.Contains(lower, "tumbleweed") || strings.Contains(lower, "opensuse"):
		return []string{
			"opensuse.tumbleweed.xml.bz2",
			"tumbleweed.xml.bz2",
		}
	case strings.Contains(lower, "rhel") || strings.Contains(lower, "red hat"):
		return []string{"rhel-10.oval.xml.bz2", "rhel-9.oval.xml.bz2"}
	case strings.Contains(lower, "rocky"):
		return []string{"rocky-linux-10.oval.xml.bz2", "rocky-linux-9.oval.xml.bz2"}
	case strings.Contains(lower, "fedora"):
		return []string{"fedora.xml.bz2"}
	default:
		return nil
	}
}

// Snapshot is the DashDiag-format CVE database (converted from OVAL).
// Stored as a separate file — never embedded in the binary.
// Binary hash remains stable; only CVE data file changes.
type Snapshot struct {
	Generated time.Time              `json:"_generated"`
	Source    string                 `json:"_source"`
	CVEs      map[string]SnapshotCVE `json:"cves"`
}

type SnapshotCVE struct {
	Summary  string                       `json:"summary"`
	Severity string                       `json:"severity"`
	Affected map[string][]SnapshotPackage `json:"affected"`
}

type SnapshotPackage struct {
	Name    string `json:"name"`
	FixedIn string `json:"fixed_in"`
}

// LoadSnapshot reads a pre-converted DashDiag snapshot file (JSON or JSON.gz).
// Snapshot files are generated by: dsd cve convert-oval /path/to/oval.xml.bz2
func LoadSnapshot(path string) (*Snapshot, error) {
	f, err := os.Open(path) // #nosec G304 -- user-supplied path intentional
	if err != nil {
		return nil, err
	}
	defer f.Close()

	var r io.Reader = f
	if strings.HasSuffix(strings.ToLower(path), ".gz") {
		gr, err := gzip.NewReader(f)
		if err != nil {
			return nil, fmt.Errorf("gzip: %w", err)
		}
		defer func() { _ = gr.Close() }()
		r = gr
	}
	if strings.HasSuffix(strings.ToLower(path), ".bz2") &&
		!strings.HasSuffix(strings.ToLower(path), ".xml.bz2") {
		r = bzip2.NewReader(f)
	}

	var s Snapshot
	if err := json.NewDecoder(r).Decode(&s); err != nil {
		return nil, fmt.Errorf("parsing snapshot: %w", err)
	}
	if s.CVEs == nil {
		s.CVEs = map[string]SnapshotCVE{}
	}
	return &s, nil
}

// SnapshotStandardPaths returns candidate locations for pre-converted snapshot files.
func SnapshotStandardPaths() []string {
	paths := []string{
		"/var/lib/dsd/cvedata.json.gz",
		"/var/lib/dsd/cvedata.json",
		"/etc/dsd/cvedata.json.gz",
	}
	if home, err := os.UserHomeDir(); err == nil {
		paths = append(paths,
			filepath.Join(home, ".local", "share", "dsd", "cvedata.json.gz"),
			filepath.Join(home, ".dsd", "cvedata.json.gz"),
		)
	}
	return paths
}

// FindSnapshot looks for a pre-converted snapshot in standard locations.
func FindSnapshot() string {
	for _, p := range SnapshotStandardPaths() {
		if _, err := os.Stat(p); err == nil {
			return p
		}
	}
	return ""
}

// IsEmpty returns true when the snapshot has no CVE data.
func (s *Snapshot) IsEmpty() bool { return len(s.CVEs) == 0 }

// Lookup finds a CVE by ID.
func (s *Snapshot) Lookup(cveID string) (SnapshotCVE, bool) {
	cve, ok := s.CVEs[cveID]
	return cve, ok
}
