#!/usr/bin/env bash
# Regenerate the Homebrew formula for a given dsd release.
#
#   scripts/gen-homebrew-formula.sh <version>     # e.g. 0.6.1 (no leading "v")
#
# Downloads the release's checksums.txt, maps each dsd-<os>-<arch> binary to its
# sha256, and renders packaging/homebrew-tap/Formula/dsd.rb. Idempotent — running
# it for an already-released version reproduces the committed formula exactly.
#
# Deps: gh (or curl) + sha256s published in the release's checksums.txt.
set -euo pipefail

VERSION="${1:?usage: gen-homebrew-formula.sh <version>  (e.g. 0.6.1)}"
VERSION="${VERSION#v}" # tolerate a leading v
TAG="v${VERSION}"
# REPO is the GitHub host of the release binaries (where the bytes actually live);
# the product homepage/brand is dashdiag.sh.
REPO="keyorixhq/dashdiag"
BASE="https://github.com/${REPO}/releases/download/${TAG}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUT="${ROOT}/packaging/homebrew-tap/Formula/dsd.rb"
TMP="$(mktemp -d)"
trap 'rm -rf "$TMP"' EXIT

# Fetch checksums.txt (gh if available, else curl).
if command -v gh >/dev/null 2>&1; then
  gh release download "$TAG" --repo "$REPO" --pattern checksums.txt --dir "$TMP" --clobber
else
  curl -fsSL "${BASE}/checksums.txt" -o "${TMP}/checksums.txt"
fi

# Pull a sha256 for a given asset name out of checksums.txt.
sha_for() {
  local asset="$1"
  local line
  line="$(grep -E "  ${asset}\$" "${TMP}/checksums.txt" || true)"
  [ -n "$line" ] || { echo "ERROR: no sha256 for ${asset} in checksums.txt" >&2; exit 1; }
  echo "${line%% *}"
}

SHA_DARWIN_ARM="$(sha_for dsd-darwin-arm64)"
SHA_DARWIN_AMD="$(sha_for dsd-darwin-amd64)"
SHA_LINUX_ARM="$(sha_for dsd-linux-arm64)"
SHA_LINUX_AMD="$(sha_for dsd-linux-amd64)"

mkdir -p "$(dirname "$OUT")"
cat > "$OUT" <<EOF
# typed: false
# frozen_string_literal: true

# Homebrew formula for dsd (DashDiag) — generated by scripts/gen-homebrew-formula.sh.
# Do not hand-edit; re-run the generator for a new release.
class Dsd < Formula
  desc "OBD diagnostics for your Linux server — one command, full picture"
  homepage "https://dashdiag.sh"
  version "${VERSION}"
  license "MIT"

  on_macos do
    on_arm do
      url "${BASE}/dsd-darwin-arm64"
      sha256 "${SHA_DARWIN_ARM}"
    end
    on_intel do
      url "${BASE}/dsd-darwin-amd64"
      sha256 "${SHA_DARWIN_AMD}"
    end
  end

  on_linux do
    on_arm do
      url "${BASE}/dsd-linux-arm64"
      sha256 "${SHA_LINUX_ARM}"
    end
    on_intel do
      url "${BASE}/dsd-linux-amd64"
      sha256 "${SHA_LINUX_AMD}"
    end
  end

  def install
    # Release assets are bare binaries named dsd-<os>-<arch>; install as "dsd".
    bin.install Dir["dsd-*"].first => "dsd"
  end

  test do
    assert_match "dsd version", shell_output("#{bin}/dsd --version")
  end
end
EOF

echo "Wrote ${OUT} for ${TAG}"
