package selfupdate

// Minisign signature verification, implemented against the minisign format
// (https://jedisct1.github.io/minisign/) with the standard library plus
// x/crypto/blake2b — no third-party signing dependency, so an air-gapped
// verifier can audit the whole path. This is the in-binary half of release
// signing: `dsd update` verifies that checksums.txt was signed by the project's
// key before trusting any hash in it, closing the self-updater single-origin gap
// (a compromised release origin can serve a matching checksum but cannot forge
// an Ed25519 signature it does not hold the secret key for).

import (
	"crypto/ed25519"
	"encoding/base64"
	"errors"
	"fmt"
	"strings"

	"golang.org/x/crypto/blake2b"
)

// minisign public keys and signatures carry a 2-byte algorithm tag:
//   "Ed" — legacy: Ed25519 over the raw file.
//   "ED" — prehashed: Ed25519 over Blake2b-512(file). The modern default.
// The signing side is our own CI, but we accept both so a key generated by any
// minisign version verifies.

// parseMinisignPublicKey accepts either a bare base64 key line or a full two-line
// .pub file and returns the key id and the Ed25519 public key.
func parseMinisignPublicKey(pub string) (keyID [8]byte, key ed25519.PublicKey, err error) {
	raw, err := base64.StdEncoding.DecodeString(lastDataLine(pub))
	if err != nil {
		return keyID, nil, fmt.Errorf("minisign public key: invalid base64: %w", err)
	}
	if len(raw) != 42 {
		return keyID, nil, fmt.Errorf("minisign public key: want 42 bytes, got %d", len(raw))
	}
	if raw[0] != 'E' || raw[1] != 'd' {
		return keyID, nil, fmt.Errorf("minisign public key: unsupported algorithm %q", raw[:2])
	}
	copy(keyID[:], raw[2:10])
	key = ed25519.PublicKey(append([]byte(nil), raw[10:42]...))
	return keyID, key, nil
}

// verifyMinisign verifies that sigFile (the contents of a `.minisig`) is a valid
// minisign signature over file, made by the key in pubLine. It checks both the
// file signature and the global signature that binds the trusted comment, and
// requires the signing key id to match the configured public key.
func verifyMinisign(pubLine string, file, sigFile []byte) error {
	keyID, pub, err := parseMinisignPublicKey(pubLine)
	if err != nil {
		return err
	}

	lines := strings.Split(strings.ReplaceAll(string(sigFile), "\r\n", "\n"), "\n")
	if len(lines) < 4 {
		return errors.New("minisign signature: malformed (need 4 lines)")
	}

	sigRaw, err := base64.StdEncoding.DecodeString(strings.TrimSpace(lines[1]))
	if err != nil {
		return fmt.Errorf("minisign signature: invalid base64: %w", err)
	}
	if len(sigRaw) != 74 {
		return fmt.Errorf("minisign signature: want 74 bytes, got %d", len(sigRaw))
	}
	algo := [2]byte{sigRaw[0], sigRaw[1]}
	var sigKeyID [8]byte
	copy(sigKeyID[:], sigRaw[2:10])
	if sigKeyID != keyID {
		return errors.New("minisign signature: key id does not match the trusted public key")
	}
	sig := sigRaw[10:74]

	// The message signed depends on the algorithm tag.
	var msg []byte
	switch algo {
	case [2]byte{'E', 'D'}: // prehashed
		h := blake2b.Sum512(file)
		msg = h[:]
	case [2]byte{'E', 'd'}: // legacy raw
		msg = file
	default:
		return fmt.Errorf("minisign signature: unsupported algorithm %q", algo[:])
	}
	if !ed25519.Verify(pub, msg, sig) {
		return errors.New("minisign signature: does not verify (file altered or wrong key)")
	}

	// Global signature binds the trusted comment: Ed25519(file_signature || trusted_comment).
	trustedComment := ""
	if tc := strings.TrimPrefix(lines[2], "trusted comment:"); tc != lines[2] {
		trustedComment = strings.TrimPrefix(tc, " ")
	}
	globalSig, err := base64.StdEncoding.DecodeString(strings.TrimSpace(lines[3]))
	if err != nil {
		return fmt.Errorf("minisign signature: invalid global-signature base64: %w", err)
	}
	bound := append(append([]byte(nil), sig...), []byte(trustedComment)...)
	if !ed25519.Verify(pub, bound, globalSig) {
		return errors.New("minisign signature: trusted comment failed verification")
	}
	return nil
}

// lastDataLine returns the last non-empty, non-comment line of s — so both a bare
// base64 line and a full minisign file (comment line + data line) work.
func lastDataLine(s string) string {
	var last string
	for _, l := range strings.Split(s, "\n") {
		l = strings.TrimSpace(l)
		if l == "" || strings.HasPrefix(l, "untrusted comment:") || strings.HasPrefix(l, "trusted comment:") {
			continue
		}
		last = l
	}
	return last
}
