package render

import (
	"fmt"
	"strings"
	"time"

	"github.com/keyorixhq/dashdiag/internal/baseline"
	"github.com/keyorixhq/dashdiag/internal/models"
	"github.com/keyorixhq/dashdiag/internal/output"
	"github.com/keyorixhq/dashdiag/internal/version"
)

func RenderPostMortem(title string, snap *baseline.Snapshot, insights []models.Insight, _ output.OutputMode) string {
	var sb strings.Builder

	now := time.Now().UTC().Format(time.RFC3339)
	fmt.Fprintf(&sb, "#### Incident: %s\n", title)
	fmt.Fprintf(&sb, "**Server:** %s  |  **Captured:** %s  |  **By:** dsd %s\n\n",
		output.SanitizeControl(snap.Hostname), now, version.Version)

	sb.WriteString("#### System State at Time of Capture\n")
	sb.WriteString("| Check | Status | Value | Threshold |\n")
	sb.WriteString("|---|---|---|---|\n")
	for _, check := range snap.Checks {
		ins := insightForResult(check.Name, insights)
		status := check.Status
		value := check.Value
		if ins != nil {
			status = ins.Level
			value = ins.Message
		}
		var statusLabel string
		switch status {
		case "WARN":
			statusLabel = "⚠️ WARN"
		case "CRIT":
			statusLabel = "❌ CRIT"
		case "INFO":
			statusLabel = "ℹ️ INFO"
		default:
			statusLabel = "✅ OK"
		}
		// check.Name/value (ins.Message) can carry attacker-controlled
		// substrings (e.g. a process name from /proc set via
		// prctl(PR_SET_NAME)) — this postmortem is explicitly designed to be
		// pasted into incident channels/tickets, and markdown doesn't escape
		// raw control/ANSI bytes any more than a terminal does. SanitizeControl
		// only strips control/ANSI bytes; a literal '|' is an ordinary
		// printable rune that would otherwise break/extend this markdown
		// table's row structure (internal-render-03-06), so escape it too.
		name := strings.ReplaceAll(output.SanitizeControl(check.Name), "|", "\\|")
		escapedValue := strings.ReplaceAll(output.SanitizeControl(value), "|", "\\|")
		fmt.Fprintf(&sb, "| %s | %s | %s | — |\n", name, statusLabel, escapedValue)
	}

	var crits, warns []models.Insight
	for _, ins := range insights {
		switch ins.Level {
		case "CRIT":
			crits = append(crits, ins)
		case "WARN":
			warns = append(warns, ins)
		}
	}

	// Message/Check/Hints below aren't wrapped in any existing backtick
	// delimiter — but attacker-influenced text containing its own run of 3+
	// backticks (e.g. embedded on its own line) can still OPEN an unintended
	// fence mid-document that swallows everything after it until a matching
	// close (or end of document), injecting arbitrary markdown/HTML into a
	// postmortem meant to be pasted into incident channels/tickets
	// (internal-render-03-06). output.SanitizeControl only strips
	// control/ANSI bytes, not backticks — escape those too.
	if len(crits)+len(warns) > 0 {
		sb.WriteString("\n#### Issues Detected\n")
		for _, ins := range crits {
			fmt.Fprintf(&sb, "- ❌ CRIT %s: %s\n",
				escapeMarkdownBackticks(output.SanitizeControl(ins.Check)),
				escapeMarkdownBackticks(output.SanitizeControl(ins.Message)))
			for _, h := range ins.Hints {
				fmt.Fprintf(&sb, "  → %s\n", escapeMarkdownBackticks(output.SanitizeControl(h)))
			}
		}
		for _, ins := range warns {
			fmt.Fprintf(&sb, "- ⚠️ WARN %s: %s\n",
				escapeMarkdownBackticks(output.SanitizeControl(ins.Check)),
				escapeMarkdownBackticks(output.SanitizeControl(ins.Message)))
			for _, h := range ins.Hints {
				fmt.Fprintf(&sb, "  → %s\n", escapeMarkdownBackticks(output.SanitizeControl(h)))
			}
		}
	}

	seen := make(map[string]bool)
	var hints []string
	for _, ins := range append(crits, warns...) {
		for _, h := range ins.Hints {
			if !seen[h] {
				seen[h] = true
				hints = append(hints, h)
			}
		}
	}
	if len(hints) > 0 {
		sb.WriteString("\n#### Recommended Investigation Steps\n")
		for i, h := range hints {
			// h is wrapped in a single-backtick inline code span here — even
			// ONE embedded backtick in h would close that span early
			// (internal-render-03-06), unlike the fenced block in report.go
			// which needs a run of 3+. escapeMarkdownBackticks neutralizes
			// every backtick unconditionally, which covers both cases.
			fmt.Fprintf(&sb, "%d. `%s`\n", i+1, escapeMarkdownBackticks(output.SanitizeControl(h)))
		}
	}

	sb.WriteString("\n#### Timeline\n")
	sb.WriteString("<!-- Paste: dsd health --diff output here -->\n")
	sb.WriteString("\n#### Resolution\n")
	sb.WriteString("<!-- Fill in -->\n")
	sb.WriteString("\n---\n")
	fmt.Fprintf(&sb, "*Generated by DashDiag %s — https://dashdiag.sh*\n", version.Version)

	return sb.String()
}
