package render

import (
	"fmt"
	"strings"
	"time"

	"github.com/keyorixhq/dashdiag/internal/baseline"
	"github.com/keyorixhq/dashdiag/internal/models"
	"github.com/keyorixhq/dashdiag/internal/output"
	"github.com/keyorixhq/dashdiag/internal/version"
)

func RenderPostMortem(title string, snap *baseline.Snapshot, insights []models.Insight, _ output.OutputMode) string {
	var sb strings.Builder

	now := time.Now().UTC().Format(time.RFC3339)
	sb.WriteString(fmt.Sprintf("#### Incident: %s\n", title))
	sb.WriteString(fmt.Sprintf("**Server:** %s  |  **Captured:** %s  |  **By:** dsd %s\n\n",
		snap.Hostname, now, version.Version))

	sb.WriteString("#### System State at Time of Capture\n")
	sb.WriteString("| Check | Status | Value | Threshold |\n")
	sb.WriteString("|---|---|---|---|\n")
	for _, check := range snap.Checks {
		ins := insightForResult(check.Name, insights)
		status := check.Status
		value := check.Value
		if ins != nil {
			status = ins.Level
			value = ins.Message
		}
		var statusLabel string
		switch status {
		case "WARN":
			statusLabel = "⚠️ WARN"
		case "CRIT":
			statusLabel = "❌ CRIT"
		case "INFO":
			statusLabel = "ℹ️ INFO"
		default:
			statusLabel = "✅ OK"
		}
		sb.WriteString(fmt.Sprintf("| %s | %s | %s | — |\n", check.Name, statusLabel, value))
	}

	var crits, warns []models.Insight
	for _, ins := range insights {
		switch ins.Level {
		case "CRIT":
			crits = append(crits, ins)
		case "WARN":
			warns = append(warns, ins)
		}
	}

	if len(crits)+len(warns) > 0 {
		sb.WriteString("\n#### Issues Detected\n")
		for _, ins := range crits {
			sb.WriteString(fmt.Sprintf("- ❌ CRIT %s: %s\n", ins.Check, ins.Message))
			for _, h := range ins.Hints {
				sb.WriteString(fmt.Sprintf("  → %s\n", h))
			}
		}
		for _, ins := range warns {
			sb.WriteString(fmt.Sprintf("- ⚠️ WARN %s: %s\n", ins.Check, ins.Message))
			for _, h := range ins.Hints {
				sb.WriteString(fmt.Sprintf("  → %s\n", h))
			}
		}
	}

	seen := make(map[string]bool)
	var hints []string
	for _, ins := range append(crits, warns...) {
		for _, h := range ins.Hints {
			if !seen[h] {
				seen[h] = true
				hints = append(hints, h)
			}
		}
	}
	if len(hints) > 0 {
		sb.WriteString("\n#### Recommended Investigation Steps\n")
		for i, h := range hints {
			sb.WriteString(fmt.Sprintf("%d. `%s`\n", i+1, h))
		}
	}

	sb.WriteString("\n#### Timeline\n")
	sb.WriteString("<!-- Paste: dsd health --diff output here -->\n")
	sb.WriteString("\n#### Resolution\n")
	sb.WriteString("<!-- Fill in -->\n")
	sb.WriteString("\n---\n")
	sb.WriteString(fmt.Sprintf("*Generated by DashDiag %s — https://dashdiag.sh*\n", version.Version))

	return sb.String()
}
