package render

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/keyorixhq/dashdiag/internal/baseline"
	"github.com/keyorixhq/dashdiag/internal/models"
	"github.com/keyorixhq/dashdiag/internal/version"
)

// GenerateReport produces a markdown health report and writes it to a file.
// Returns the output file path.
func GenerateReport(snap *baseline.Snapshot, insights []models.Insight, elapsed time.Duration) (string, error) {
	if snap == nil {
		return "", fmt.Errorf("no snapshot data")
	}

	md := buildMarkdown(snap, insights, elapsed)

	timestamp := snap.Timestamp.Format("20060102-150405")
	filename := fmt.Sprintf("dsd-report-%s-%s.md", snap.Hostname, timestamp)
	path := filepath.Join(".", filename)

	if err := os.WriteFile(path, []byte(md), 0o644); err != nil { //nolint:gosec // report file, world-readable intentional
		return "", fmt.Errorf("writing report: %w", err)
	}
	return path, nil
}

func buildMarkdown(snap *baseline.Snapshot, insights []models.Insight, elapsed time.Duration) string {
	var b strings.Builder

	crits := countLevel(insights, "CRIT")
	warns := countLevel(insights, "WARN")
	total := crits + warns

	// Header
	fmt.Fprintf(&b, "# DashDiag Health Report\n\n")
	fmt.Fprintf(&b, "**Host:** `%s`  \n", snap.Hostname)
	fmt.Fprintf(&b, "**Date:** %s  \n", snap.Timestamp.Format("2006-01-02 15:04:05 MST"))
	fmt.Fprintf(&b, "**Scan time:** %.1fs  \n", elapsed.Seconds())
	fmt.Fprintf(&b, "**Version:** %s  \n\n", version.Version)

	// Summary
	fmt.Fprintf(&b, "## Summary\n\n")
	if total == 0 {
		fmt.Fprintf(&b, "✅ **All checks passed** — system is healthy.\n\n")
	} else {
		if crits > 0 {
			fmt.Fprintf(&b, "🔴 **%d critical** issue(s) require immediate attention.  \n", crits)
		}
		if warns > 0 {
			fmt.Fprintf(&b, "⚠️  **%d warning(s)** found.  \n", warns)
		}
		fmt.Fprintf(&b, "\n")
	}

	// Issues — CRIT first, then WARN
	actionable := filterActionable(insights)
	if len(actionable) > 0 {
		fmt.Fprintf(&b, "## Issues\n\n")
		for _, ins := range actionable {
			icon := "⚠️"
			if ins.Level == "CRIT" {
				icon = "🔴"
			}
			fmt.Fprintf(&b, "### %s %s — %s\n\n", icon, ins.Level, ins.Check)
			fmt.Fprintf(&b, "%s\n\n", ins.Message)
			if len(ins.Hints) > 0 {
				fmt.Fprintf(&b, "**Remediation:**\n")
				for _, h := range ins.Hints {
					fmt.Fprintf(&b, "```\n%s\n```\n", h)
				}
				fmt.Fprintf(&b, "\n")
			}
		}
	}

	// Check results table
	fmt.Fprintf(&b, "## Check Results\n\n")
	fmt.Fprintf(&b, "| Check | Status |\n")
	fmt.Fprintf(&b, "|---|---|\n")

	warnChecks := map[string]bool{}
	critChecks := map[string]bool{}
	for _, ins := range insights {
		switch ins.Level {
		case "CRIT":
			critChecks[ins.Check] = true
		case "WARN":
			warnChecks[ins.Check] = true
		}
	}

	for _, check := range snap.Checks {
		status := "✅ OK"
		if critChecks[check.Name] {
			status = "🔴 CRIT"
		} else if warnChecks[check.Name] {
			status = "⚠️ WARN"
		}
		fmt.Fprintf(&b, "| %s | %s |\n", check.Name, status)
	}
	fmt.Fprintf(&b, "\n")

	// Footer
	fmt.Fprintf(&b, "---\n")
	fmt.Fprintf(&b, "*Generated by [DashDiag](https://github.com/keyorixhq/dashdiag) %s — [dashdiag.dev](https://dashdiag.dev)*\n",
		version.Version)

	return b.String()
}

func filterActionable(insights []models.Insight) []models.Insight {
	var out []models.Insight
	for _, ins := range insights {
		if ins.Level == "CRIT" || ins.Level == "WARN" {
			out = append(out, ins)
		}
	}
	sort.Slice(out, func(i, j int) bool {
		if out[i].Level != out[j].Level {
			return out[i].Level == "CRIT"
		}
		return out[i].Check < out[j].Check
	})
	return out
}

func countLevel(insights []models.Insight, level string) int {
	n := 0
	for _, ins := range insights {
		if ins.Level == level {
			n++
		}
	}
	return n
}
