//go:build linux

package collectors

import (
	"testing"

	"github.com/keyorixhq/dashdiag/internal/models"
	"github.com/keyorixhq/dashdiag/internal/source"
)

func TestParseResolvConf(t *testing.T) {
	withFixtureSource(t, func(b *source.Bundle) {
		b.PutFile("/etc/resolv.conf", []byte(
			"# generated by resolvconf\n"+
				"nameserver 1.1.1.1\n"+
				"nameserver 8.8.8.8\n"+
				"nameserver 1.1.1.1\n"+ // duplicate — must be tracked separately
				"search example.com internal.example.com\n"+
				"options ndots:5 timeout:2\n",
		))
	})
	info := &models.DNSResolverInfo{}
	parseResolvConf(info)

	if len(info.Nameservers) != 2 || info.Nameservers[0] != "1.1.1.1" || info.Nameservers[1] != "8.8.8.8" {
		t.Errorf("nameservers should be deduped into the primary list, got %v", info.Nameservers)
	}
	if len(info.DuplicateNameserver) != 1 || info.DuplicateNameserver[0] != "1.1.1.1" {
		t.Errorf("the repeated nameserver should be tracked as a duplicate, got %v", info.DuplicateNameserver)
	}
	if len(info.SearchDomains) != 2 {
		t.Errorf("both search domains should be captured, got %v", info.SearchDomains)
	}
	if len(info.Options) != 2 {
		t.Errorf("both options should be captured, got %v", info.Options)
	}
}
