//go:build linux

package collectors

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/keyorixhq/dashdiag/internal/models"
	"github.com/keyorixhq/dashdiag/internal/source"
)

func TestDNSCollectorIdentity(t *testing.T) {
	t.Parallel()
	c := NewDNSCollector()
	if c.Name() != "DNS" {
		t.Errorf("Name() = %q, want DNS", c.Name())
	}
	if c.Timeout() != 8*time.Second {
		t.Errorf("Timeout() = %v, want 8s", c.Timeout())
	}
}

// TestDetectDNSManager_SystemdResolved guards the systemd-resolved branch: a
// stub-mode resolv.conf (or a "systemd"-named config file) with
// systemd-resolved reporting active must be attributed to it.
func TestDetectDNSManager_SystemdResolved(t *testing.T) {
	withCombinedFixture(t, nil, nil, func(b *source.Bundle) {
		b.PutCmd("systemctl", []string{"is-active", "systemd-resolved"}, "active\n", 0)
	})
	info := &models.DNSResolverInfo{ConfigFile: "/run/systemd/resolve/stub-resolv.conf", StubMode: true}
	detectDNSManager(context.Background(), info)
	if info.Manager != "systemd-resolved" {
		t.Errorf("Manager = %q, want systemd-resolved", info.Manager)
	}
}

// TestDetectDNSManager_NetworkManager guards the NetworkManager fallback: NM
// must be reported active AND resolv.conf must actually reference it — either
// alone is not enough to attribute DNS management to NM.
func TestDetectDNSManager_NetworkManager(t *testing.T) {
	withCombinedFixture(t, nil, nil, func(b *source.Bundle) {
		b.PutCmd("systemctl", []string{"is-active", "NetworkManager"}, "active\n", 0)
		b.PutFile("/etc/resolv.conf", []byte("# Generated by NetworkManager\nnameserver 192.168.1.1\n"))
	})
	info := &models.DNSResolverInfo{ConfigFile: "/etc/resolv.conf"}
	detectDNSManager(context.Background(), info)
	if info.Manager != "NetworkManager" {
		t.Errorf("Manager = %q, want NetworkManager", info.Manager)
	}
}

// TestDetectDNSManager_StaticFallback guards the static fallback: neither
// systemd-resolved nor NetworkManager active, but nameservers are configured.
func TestDetectDNSManager_StaticFallback(t *testing.T) {
	withCombinedFixture(t, nil, nil, func(b *source.Bundle) {
		b.PutCmdNotFound("systemctl", []string{"is-active", "NetworkManager"})
	})
	info := &models.DNSResolverInfo{ConfigFile: "/etc/resolv.conf", Nameservers: []string{"1.1.1.1"}}
	detectDNSManager(context.Background(), info)
	if info.Manager != "static" {
		t.Errorf("Manager = %q, want static", info.Manager)
	}
}

// TestDetectDNSManager_NoneFallback guards the final fallback: no manager
// detected and no nameservers configured either.
func TestDetectDNSManager_NoneFallback(t *testing.T) {
	withCombinedFixture(t, nil, nil, func(b *source.Bundle) {
		b.PutCmdNotFound("systemctl", []string{"is-active", "NetworkManager"})
	})
	info := &models.DNSResolverInfo{ConfigFile: "/etc/resolv.conf"}
	detectDNSManager(context.Background(), info)
	if info.Manager != "none" {
		t.Errorf("Manager = %q, want none", info.Manager)
	}
}

func TestAnalyzeDNSQuality(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		info models.DNSResolverInfo
		want models.DNSResolverInfo // only the fields under test are checked
	}{
		{
			name: "too many nameservers",
			info: models.DNSResolverInfo{Nameservers: []string{"10.0.0.1", "10.0.0.2", "10.0.0.3", "10.0.0.4"}},
			want: models.DNSResolverInfo{TooManyNameservers: true},
		},
		{
			name: "loopback nameserver when not stub mode",
			info: models.DNSResolverInfo{Nameservers: []string{"127.0.0.1"}, StubMode: false},
			want: models.DNSResolverInfo{HasLoopback: true},
		},
		{
			name: "loopback nameserver in stub mode is not flagged",
			info: models.DNSResolverInfo{Nameservers: []string{"127.0.0.53"}, StubMode: true},
			want: models.DNSResolverInfo{},
		},
		{
			name: "high ndots",
			info: models.DNSResolverInfo{Options: []string{"ndots:5"}},
			want: models.DNSResolverInfo{NdotsHigh: 5},
		},
		{
			name: "ndots at boundary not flagged",
			info: models.DNSResolverInfo{Options: []string{"ndots:3"}},
			want: models.DNSResolverInfo{},
		},
		{
			name: "all IPv6 nameservers",
			info: models.DNSResolverInfo{Nameservers: []string{"2001:db8::1"}},
			want: models.DNSResolverInfo{IPv6Only: true},
		},
		{
			name: "mixed v4/v6 is not IPv6-only",
			info: models.DNSResolverInfo{Nameservers: []string{"2001:db8::1", "10.0.0.1"}},
			want: models.DNSResolverInfo{},
		},
		{
			name: "public DNS fallback flagged",
			info: models.DNSResolverInfo{Nameservers: []string{"8.8.8.8"}},
			want: models.DNSResolverInfo{PublicFallback: true},
		},
		{
			name: "combined: too many + public + high ndots",
			info: models.DNSResolverInfo{
				Nameservers: []string{"8.8.8.8", "1.1.1.1", "9.9.9.9", "10.0.0.1"},
				Options:     []string{"ndots:4"},
			},
			want: models.DNSResolverInfo{TooManyNameservers: true, PublicFallback: true, NdotsHigh: 4},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			info := tt.info
			analyzeDNSQuality(&info)
			if info.TooManyNameservers != tt.want.TooManyNameservers {
				t.Errorf("TooManyNameservers = %v, want %v", info.TooManyNameservers, tt.want.TooManyNameservers)
			}
			if info.HasLoopback != tt.want.HasLoopback {
				t.Errorf("HasLoopback = %v, want %v", info.HasLoopback, tt.want.HasLoopback)
			}
			if info.NdotsHigh != tt.want.NdotsHigh {
				t.Errorf("NdotsHigh = %v, want %v", info.NdotsHigh, tt.want.NdotsHigh)
			}
			if info.IPv6Only != tt.want.IPv6Only {
				t.Errorf("IPv6Only = %v, want %v", info.IPv6Only, tt.want.IPv6Only)
			}
			if info.PublicFallback != tt.want.PublicFallback {
				t.Errorf("PublicFallback = %v, want %v", info.PublicFallback, tt.want.PublicFallback)
			}
		})
	}
}

// TestDNSCollector_Collect_FullHappyPath drives Collect() end to end: a real
// resolv.conf, a systemd-resolved manager, and a cached probe result — all
// three pipeline stages (parse/detect/probe/analyze) wired together, without
// touching the network (runDNSProbeLive is never invoked because the
// "dns/resolve-probe" cache key is pre-seeded).
func TestDNSCollector_Collect_FullHappyPath(t *testing.T) {
	probe := dnsProbeResult{ExternalLatencyMs: 12, ExternalResolvesOK: true, InternalResolvesOK: true}
	probeJSON, err := json.Marshal(probe)
	if err != nil {
		t.Fatalf("marshal dnsProbeResult: %v", err)
	}
	withCombinedFixture(t, map[string][]byte{
		"dns/resolve-probe": probeJSON,
	}, nil, func(b *source.Bundle) {
		b.PutFile("/etc/resolv.conf", []byte("nameserver 127.0.0.53\noptions ndots:1\n"))
		b.PutCmd("systemctl", []string{"is-active", "systemd-resolved"}, "active\n", 0)
	})

	c := NewDNSCollector()
	raw, err := c.Collect(context.Background())
	if err != nil {
		t.Fatalf("Collect() error: %v", err)
	}
	info := raw.(*models.DNSResolverInfo)
	if !info.Available {
		t.Error("Available = false, want true")
	}
	if info.Manager != "systemd-resolved" {
		t.Errorf("Manager = %q, want systemd-resolved", info.Manager)
	}
	if !info.StubMode {
		t.Error("StubMode = false, want true (127.0.0.53)")
	}
	if !info.ExternalResolvesOK || info.ExternalLatencyMs != 12 {
		t.Errorf("ExternalResolvesOK=%v ExternalLatencyMs=%d, want true/12", info.ExternalResolvesOK, info.ExternalLatencyMs)
	}
	if info.HasLoopback {
		t.Error("HasLoopback = true, want false (stub mode suppresses the loopback flag)")
	}
}

func TestParseResolvConf(t *testing.T) {
	withFixtureSource(t, func(b *source.Bundle) {
		b.PutFile("/etc/resolv.conf", []byte(
			"# generated by resolvconf\n"+
				"nameserver 1.1.1.1\n"+
				"nameserver 8.8.8.8\n"+
				"nameserver 1.1.1.1\n"+ // duplicate — must be tracked separately
				"search example.com internal.example.com\n"+
				"options ndots:5 timeout:2\n",
		))
	})
	info := &models.DNSResolverInfo{}
	parseResolvConf(info)

	if len(info.Nameservers) != 2 || info.Nameservers[0] != "1.1.1.1" || info.Nameservers[1] != "8.8.8.8" {
		t.Errorf("nameservers should be deduped into the primary list, got %v", info.Nameservers)
	}
	if len(info.DuplicateNameserver) != 1 || info.DuplicateNameserver[0] != "1.1.1.1" {
		t.Errorf("the repeated nameserver should be tracked as a duplicate, got %v", info.DuplicateNameserver)
	}
	if len(info.SearchDomains) != 2 {
		t.Errorf("both search domains should be captured, got %v", info.SearchDomains)
	}
	if len(info.Options) != 2 {
		t.Errorf("both options should be captured, got %v", info.Options)
	}
}
