//go:build linux

package collectors

import (
	"context"
	"encoding/json"
	"testing"
	"time"

	"github.com/keyorixhq/dashdiag/internal/models"
	"github.com/keyorixhq/dashdiag/internal/source"
)

func TestDNSCollectorIdentity(t *testing.T) {
	t.Parallel()
	c := NewDNSCollector()
	if c.Name() != "DNS" {
		t.Errorf("Name() = %q, want DNS", c.Name())
	}
	if c.Timeout() != 8*time.Second {
		t.Errorf("Timeout() = %v, want 8s", c.Timeout())
	}
}

// TestDetectDNSManager_SystemdResolved guards the systemd-resolved branch: a
// stub-mode resolv.conf (or a "systemd"-named config file) with
// systemd-resolved reporting active must be attributed to it.
func TestDetectDNSManager_SystemdResolved(t *testing.T) {
	withCombinedFixture(t, nil, nil, func(b *source.Bundle) {
		b.PutCmd("systemctl", []string{"is-active", "systemd-resolved"}, "active\n", 0)
	})
	info := &models.DNSResolverInfo{ConfigFile: "/run/systemd/resolve/stub-resolv.conf", StubMode: true}
	detectDNSManager(context.Background(), info)
	if info.Manager != "systemd-resolved" {
		t.Errorf("Manager = %q, want systemd-resolved", info.Manager)
	}
}

// TestDetectDNSManager_NetworkManager guards the NetworkManager fallback: NM
// must be reported active AND resolv.conf must actually reference it — either
// alone is not enough to attribute DNS management to NM.
func TestDetectDNSManager_NetworkManager(t *testing.T) {
	withCombinedFixture(t, nil, nil, func(b *source.Bundle) {
		b.PutCmd("systemctl", []string{"is-active", "NetworkManager"}, "active\n", 0)
		b.PutFile("/etc/resolv.conf", []byte("# Generated by NetworkManager\nnameserver 192.168.1.1\n"))
	})
	info := &models.DNSResolverInfo{ConfigFile: "/etc/resolv.conf"}
	detectDNSManager(context.Background(), info)
	if info.Manager != "NetworkManager" {
		t.Errorf("Manager = %q, want NetworkManager", info.Manager)
	}
}

// TestDetectDNSManager_StaticFallback guards the static fallback: neither
// systemd-resolved nor NetworkManager active, but nameservers are configured.
func TestDetectDNSManager_StaticFallback(t *testing.T) {
	withCombinedFixture(t, nil, nil, func(b *source.Bundle) {
		b.PutCmdNotFound("systemctl", []string{"is-active", "NetworkManager"})
	})
	info := &models.DNSResolverInfo{ConfigFile: "/etc/resolv.conf", Nameservers: []string{"1.1.1.1"}}
	detectDNSManager(context.Background(), info)
	if info.Manager != "static" {
		t.Errorf("Manager = %q, want static", info.Manager)
	}
}

// TestDetectDNSManager_NoneFallback guards the final fallback: no manager
// detected and no nameservers configured either.
func TestDetectDNSManager_NoneFallback(t *testing.T) {
	withCombinedFixture(t, nil, nil, func(b *source.Bundle) {
		b.PutCmdNotFound("systemctl", []string{"is-active", "NetworkManager"})
	})
	info := &models.DNSResolverInfo{ConfigFile: "/etc/resolv.conf"}
	detectDNSManager(context.Background(), info)
	if info.Manager != "none" {
		t.Errorf("Manager = %q, want none", info.Manager)
	}
}

func TestAnalyzeDNSQuality(t *testing.T) {
	t.Parallel()
	tests := []struct {
		name string
		info models.DNSResolverInfo
		want models.DNSResolverInfo // only the fields under test are checked
	}{
		{
			name: "too many nameservers",
			info: models.DNSResolverInfo{Nameservers: []string{"10.0.0.1", "10.0.0.2", "10.0.0.3", "10.0.0.4"}},
			want: models.DNSResolverInfo{TooManyNameservers: true},
		},
		{
			name: "loopback nameserver when not stub mode",
			info: models.DNSResolverInfo{Nameservers: []string{"127.0.0.1"}, StubMode: false},
			want: models.DNSResolverInfo{HasLoopback: true},
		},
		{
			name: "loopback nameserver in stub mode is not flagged",
			info: models.DNSResolverInfo{Nameservers: []string{"127.0.0.53"}, StubMode: true},
			want: models.DNSResolverInfo{},
		},
		{
			name: "high ndots",
			info: models.DNSResolverInfo{Options: []string{"ndots:5"}},
			want: models.DNSResolverInfo{NdotsHigh: 5},
		},
		{
			name: "ndots at boundary not flagged",
			info: models.DNSResolverInfo{Options: []string{"ndots:3"}},
			want: models.DNSResolverInfo{},
		},
		{
			name: "all IPv6 nameservers",
			info: models.DNSResolverInfo{Nameservers: []string{"2001:db8::1"}},
			want: models.DNSResolverInfo{IPv6Only: true},
		},
		{
			name: "mixed v4/v6 is not IPv6-only",
			info: models.DNSResolverInfo{Nameservers: []string{"2001:db8::1", "10.0.0.1"}},
			want: models.DNSResolverInfo{},
		},
		{
			name: "public DNS fallback flagged",
			info: models.DNSResolverInfo{Nameservers: []string{"8.8.8.8"}},
			want: models.DNSResolverInfo{PublicFallback: true},
		},
		{
			name: "combined: too many + public + high ndots",
			info: models.DNSResolverInfo{
				Nameservers: []string{"8.8.8.8", "1.1.1.1", "9.9.9.9", "10.0.0.1"},
				Options:     []string{"ndots:4"},
			},
			want: models.DNSResolverInfo{TooManyNameservers: true, PublicFallback: true, NdotsHigh: 4},
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			t.Parallel()
			info := tt.info
			analyzeDNSQuality(&info)
			if info.TooManyNameservers != tt.want.TooManyNameservers {
				t.Errorf("TooManyNameservers = %v, want %v", info.TooManyNameservers, tt.want.TooManyNameservers)
			}
			if info.HasLoopback != tt.want.HasLoopback {
				t.Errorf("HasLoopback = %v, want %v", info.HasLoopback, tt.want.HasLoopback)
			}
			if info.NdotsHigh != tt.want.NdotsHigh {
				t.Errorf("NdotsHigh = %v, want %v", info.NdotsHigh, tt.want.NdotsHigh)
			}
			if info.IPv6Only != tt.want.IPv6Only {
				t.Errorf("IPv6Only = %v, want %v", info.IPv6Only, tt.want.IPv6Only)
			}
			if info.PublicFallback != tt.want.PublicFallback {
				t.Errorf("PublicFallback = %v, want %v", info.PublicFallback, tt.want.PublicFallback)
			}
		})
	}
}

// TestAnalyzeDNSQuality_NdotsOverflowDoesNotWrapNegative guards against an
// integer-overflow false negative. resolv.conf's ndots option is attacker-
// influenced (DHCP-supplied, or a hostile K8s admission webhook/CNI writing
// a pod's resolv.conf), so a pathologically long digit string must not wrap
// Go's int around via naive n = n*10+digit accumulation. 19 nines exceeds
// int64's range and — without a cap — wraps to exactly 0, which silently
// defeats the "n > 3" check and hides a genuine high-ndots hazard.
func TestAnalyzeDNSQuality_NdotsOverflowDoesNotWrapNegative(t *testing.T) {
	t.Parallel()
	info := &models.DNSResolverInfo{Options: []string{"ndots:9999999999999999999"}} // 19 nines
	analyzeDNSQuality(info)
	if info.NdotsHigh <= 3 {
		t.Errorf("NdotsHigh = %d, want > 3 (a pathologically long ndots value must still be flagged, not overflow-wrap to a false negative)", info.NdotsHigh)
	}
}

// TestDNSCollector_Collect_FullHappyPath drives Collect() end to end: a real
// resolv.conf, a systemd-resolved manager, and a cached probe result — all
// three pipeline stages (parse/detect/probe/analyze) wired together, without
// touching the network (runDNSProbeLive is never invoked because the
// "dns/resolve-probe" cache key is pre-seeded).
func TestDNSCollector_Collect_FullHappyPath(t *testing.T) {
	probe := dnsProbeResult{ExternalLatencyMs: 12, ExternalResolvesOK: true, InternalResolvesOK: true}
	probeJSON, err := json.Marshal(probe)
	if err != nil {
		t.Fatalf("marshal dnsProbeResult: %v", err)
	}
	withCombinedFixture(t, map[string][]byte{
		"dns/resolve-probe": probeJSON,
	}, nil, func(b *source.Bundle) {
		b.PutFile("/etc/resolv.conf", []byte("nameserver 127.0.0.53\noptions ndots:1\n"))
		b.PutCmd("systemctl", []string{"is-active", "systemd-resolved"}, "active\n", 0)
	})

	c := NewDNSCollector()
	raw, err := c.Collect(context.Background())
	if err != nil {
		t.Fatalf("Collect() error: %v", err)
	}
	info := raw.(*models.DNSResolverInfo)
	if !info.Available {
		t.Error("Available = false, want true")
	}
	if info.Manager != "systemd-resolved" {
		t.Errorf("Manager = %q, want systemd-resolved", info.Manager)
	}
	if !info.StubMode {
		t.Error("StubMode = false, want true (127.0.0.53)")
	}
	if !info.ExternalResolvesOK || info.ExternalLatencyMs != 12 {
		t.Errorf("ExternalResolvesOK=%v ExternalLatencyMs=%d, want true/12", info.ExternalResolvesOK, info.ExternalLatencyMs)
	}
	if info.HasLoopback {
		t.Error("HasLoopback = true, want false (stub mode suppresses the loopback flag)")
	}
}

// TestRunDNSProbeLive_CanceledContext guards the error branch: a context
// that's already canceled must make the external LookupHost("google.com")
// call fail immediately (context.Canceled), so ExternalResolvesOK stays false
// and ResolvTestError is populated — deterministic and network-independent,
// since the Go resolver checks ctx.Err() before attempting any external I/O.
// (InternalResolvesOK is not asserted here: the hostname lookup can resolve
// purely from /etc/hosts/NSS without any network I/O, so it may still succeed
// even on a canceled context — that's environment-dependent, not part of this
// guard.)
func TestRunDNSProbeLive_CanceledContext(t *testing.T) {
	t.Parallel()
	ctx, cancel := context.WithCancel(context.Background())
	cancel()

	pr := runDNSProbeLive(ctx)
	if pr.ExternalResolvesOK {
		t.Error("ExternalResolvesOK = true with a canceled context, want false")
	}
	if pr.ResolvTestError == "" {
		t.Error("ResolvTestError should be populated when LookupHost fails on a canceled context")
	}
}

// TestRunDNSProbe_DSD_OFFLINE_SkipsLiveLookup is the regression test for
// internal-collectors-09-01: runDNSProbe used to unconditionally resolve
// google.com (and the host's own hostname) with no opt-out, unlike every
// other live network probe in the codebase. With DSD_OFFLINE set, it must
// set ProbeSkipped and return without ever reaching cachedJSON("dns/resolve-
// probe", ...) — proven by recording every Cached() key requested rather
// than by inspecting resolution fields (which would require an actual
// network lookup on a fix-reverted build).
func TestRunDNSProbe_DSD_OFFLINE_SkipsLiveLookup(t *testing.T) {
	t.Setenv("DSD_OFFLINE", "1")
	var calls []string
	prev := SetSource(recordingCacheSource{Replay: source.NewReplay(source.NewBundle()), calls: &calls})
	defer SetSource(prev)

	info := &models.DNSResolverInfo{}
	runDNSProbe(context.Background(), info)

	if !info.ProbeSkipped {
		t.Error("expected ProbeSkipped=true when DSD_OFFLINE is set")
	}
	if info.ExternalResolvesOK || info.InternalResolvesOK {
		t.Errorf("expected no resolution result when skipped, got %+v", info)
	}
	for _, k := range calls {
		if k == "dns/resolve-probe" {
			t.Fatal(`cachedJSON("dns/resolve-probe", ...) was called despite DSD_OFFLINE — the live lookup path was reached`)
		}
	}
}

func TestParseResolvConf(t *testing.T) {
	withFixtureSource(t, func(b *source.Bundle) {
		b.PutFile("/etc/resolv.conf", []byte(
			"# generated by resolvconf\n"+
				"nameserver 1.1.1.1\n"+
				"nameserver 8.8.8.8\n"+
				"nameserver 1.1.1.1\n"+ // duplicate — must be tracked separately
				"search example.com internal.example.com\n"+
				"options ndots:5 timeout:2\n"+
				"sortlist\n", // a directive with no value — fewer than 2 fields, must be skipped
		))
	})
	info := &models.DNSResolverInfo{}
	parseResolvConf(info)

	if len(info.Nameservers) != 2 || info.Nameservers[0] != "1.1.1.1" || info.Nameservers[1] != "8.8.8.8" {
		t.Errorf("nameservers should be deduped into the primary list, got %v", info.Nameservers)
	}
	if len(info.DuplicateNameserver) != 1 || info.DuplicateNameserver[0] != "1.1.1.1" {
		t.Errorf("the repeated nameserver should be tracked as a duplicate, got %v", info.DuplicateNameserver)
	}
	if len(info.SearchDomains) != 2 {
		t.Errorf("both search domains should be captured, got %v", info.SearchDomains)
	}
	if len(info.Options) != 2 {
		t.Errorf("both options should be captured, got %v", info.Options)
	}
}

// TestParseResolvConf_SymlinkResolved guards the readLink success branch: when
// /etc/resolv.conf is a symlink (the systemd-resolved case), ConfigFile must
// report the RESOLVED target, not the literal "/etc/resolv.conf" path — that
// target is what detectDNSManager keys its "systemd" substring match on.
func TestParseResolvConf_SymlinkResolved(t *testing.T) {
	withCombinedFixture(t, nil, map[string]string{
		"/etc/resolv.conf": "/run/systemd/resolve/stub-resolv.conf",
	}, func(b *source.Bundle) {
		b.PutFile("/etc/resolv.conf", []byte("nameserver 127.0.0.53\n"))
	})
	info := &models.DNSResolverInfo{}
	parseResolvConf(info)
	if info.ConfigFile != "/run/systemd/resolve/stub-resolv.conf" {
		t.Errorf("ConfigFile = %q, want the resolved symlink target", info.ConfigFile)
	}
}

// TestParseResolvConf_MissingFile guards the "resolv.conf can't be read" early
// return: ConfigFile still falls back to the literal path (readLink also
// errors, since nothing was seeded), and no nameservers/options are parsed.
func TestParseResolvConf_MissingFile(t *testing.T) {
	withFixtureSource(t, func(b *source.Bundle) {}) // /etc/resolv.conf never seeded
	info := &models.DNSResolverInfo{}
	parseResolvConf(info)
	if info.ConfigFile != "/etc/resolv.conf" {
		t.Errorf("ConfigFile = %q, want the literal path when readLink also fails", info.ConfigFile)
	}
	if len(info.Nameservers) != 0 || len(info.Options) != 0 {
		t.Errorf("expected no nameservers/options parsed from a missing file, got %+v", info)
	}
}
