//go:build linux

package collectors

import (
	"context"
	"net"
	"os"
	"strings"
	"time"

	"github.com/keyorixhq/dashdiag/internal/models"
)

// DNSCollector audits the DNS resolver configuration.
// Reads /etc/resolv.conf, detects the manager (systemd-resolved vs
// NetworkManager vs static), and runs a live resolution test.
type DNSCollector struct{}

func NewDNSCollector() *DNSCollector { return &DNSCollector{} }

func (c *DNSCollector) Name() string           { return "DNS" }
func (c *DNSCollector) Timeout() time.Duration { return 8 * time.Second }

func (c *DNSCollector) Collect(ctx context.Context) (interface{}, error) {
	info := &models.DNSResolverInfo{Available: true}

	parseResolvConf(info)
	detectDNSManager(ctx, info)
	runDNSProbe(ctx, info)
	analyzeDNSQuality(info)

	return info, nil
}

// parseResolvConf reads /etc/resolv.conf directly.
// This is the ground truth regardless of what manages it.
func parseResolvConf(info *models.DNSResolverInfo) {
	// Resolve symlink to find the real target
	target, err := os.Readlink("/etc/resolv.conf")
	if err == nil {
		info.ConfigFile = target
	} else {
		info.ConfigFile = "/etc/resolv.conf"
	}

	data, err := os.ReadFile("/etc/resolv.conf") // #nosec G304 -- hardcoded system file
	if err != nil {
		return
	}

	seen := map[string]bool{}
	for _, line := range strings.Split(string(data), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") || strings.HasPrefix(line, ";") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) < 2 {
			continue
		}
		switch fields[0] {
		case "nameserver":
			ip := fields[1]
			if seen[ip] {
				info.DuplicateNameserver = append(info.DuplicateNameserver, ip)
			} else {
				seen[ip] = true
				info.Nameservers = append(info.Nameservers, ip)
			}
		case "search", "domain":
			info.SearchDomains = append(info.SearchDomains, fields[1:]...)
		case "options":
			info.Options = append(info.Options, fields[1:]...)
		}
	}

	// Stub mode: systemd-resolved stub resolver
	for _, ns := range info.Nameservers {
		if ns == "127.0.0.53" || ns == "::1" {
			info.StubMode = true
			break
		}
	}
}

// detectDNSManager identifies what is managing /etc/resolv.conf.
func detectDNSManager(ctx context.Context, info *models.DNSResolverInfo) {
	// systemd-resolved: resolv.conf is a symlink to /run/systemd/resolve/stub-resolv.conf
	// or /run/systemd/resolve/resolv.conf
	if strings.Contains(info.ConfigFile, "systemd") || info.StubMode {
		out, err := runCmd(ctx, "systemctl", "is-active", "systemd-resolved")
		if err == nil && strings.TrimSpace(out) == "active" {
			info.Manager = "systemd-resolved"
			return
		}
	}

	// NetworkManager: check if NM is active and managing DNS
	out, err := runCmd(ctx, "systemctl", "is-active", "NetworkManager")
	if err == nil && strings.TrimSpace(out) == "active" {
		// Confirm NM is actually writing resolv.conf
		data, _ := os.ReadFile("/etc/resolv.conf") // #nosec G304
		if strings.Contains(string(data), "Generated by NetworkManager") ||
			strings.Contains(string(data), "NetworkManager") {
			info.Manager = "NetworkManager"
			return
		}
	}

	// Static: no manager detected
	if len(info.Nameservers) > 0 {
		info.Manager = "static"
	} else {
		info.Manager = "none"
	}
}

// runDNSProbe tests external and internal resolution with a timeout.
func runDNSProbe(ctx context.Context, info *models.DNSResolverInfo) {
	// Cap probe to 5 seconds regardless of collector timeout
	probeCtx, cancel := context.WithTimeout(ctx, 5*time.Second)
	defer cancel()

	// External resolution test using the system resolver
	start := time.Now()
	r := &net.Resolver{PreferGo: true}
	addrs, err := r.LookupHost(probeCtx, "google.com")
	info.ExternalLatencyMs = int(time.Since(start).Milliseconds())

	if err == nil && len(addrs) > 0 {
		info.ExternalResolvesOK = true
	} else if err != nil {
		info.ResolvTestError = err.Error()
	}

	// Internal: can we resolve our own hostname?
	hostname, _ := os.Hostname()
	if hostname != "" {
		if _, err := r.LookupHost(probeCtx, hostname); err == nil {
			info.InternalResolvesOK = true
		}
	}
}

// analyzeDNSQuality sets quality flags based on parsed config.
func analyzeDNSQuality(info *models.DNSResolverInfo) {
	// libc silently ignores more than 3 nameservers
	if len(info.Nameservers) > 3 {
		info.TooManyNameservers = true
	}

	// Loopback nameserver that isn't the systemd stub (misconfiguration)
	if !info.StubMode {
		for _, ns := range info.Nameservers {
			if strings.HasPrefix(ns, "127.") {
				info.HasLoopback = true
				break
			}
		}
	}

	// High ndots — causes every hostname to be tried as FQDN first (Kubernetes hazard)
	for _, opt := range info.Options {
		if strings.HasPrefix(opt, "ndots:") {
			n := 0
			for _, c := range opt[6:] {
				if c >= '0' && c <= '9' {
					n = n*10 + int(c-'0')
				}
			}
			if n > 3 {
				info.NdotsHigh = n
			}
		}
	}

	// All IPv6 resolvers — no IPv4 fallback
	hasIPv4 := false
	for _, ns := range info.Nameservers {
		if !strings.Contains(ns, ":") {
			hasIPv4 = true
			break
		}
	}
	if len(info.Nameservers) > 0 && !hasIPv4 {
		info.IPv6Only = true
	}

	// Public DNS servers (privacy concern on corporate/server networks)
	publicDNS := map[string]bool{
		"8.8.8.8": true, "8.8.4.4": true, // Google
		"1.1.1.1": true, "1.0.0.1": true, // Cloudflare
		"9.9.9.9": true, "149.112.112.112": true, // Quad9
		"208.67.222.222": true, "208.67.220.220": true, // OpenDNS
	}
	for _, ns := range info.Nameservers {
		if publicDNS[ns] {
			info.PublicFallback = true
			break
		}
	}
}
